### PR TITLE
Update ctapipe_io_lst and add `--flatfield-heuristic` switch to relevant programs

### PR DESCRIPTION
**Pull request by maxnoe**
Adding a switch to disable the flatfield heuristic in the onsite scripts that need it

### CODE REVIEW

**Review by moralejo — DISMISSED** [review]

**Comment by maxnoe** [comment]
Discussed with @moralejo: We want to switch the default. So no option should be not using the heuristic and for old data we add the switch. However, this needs change of the default in `ctapipe_io_lst` (or adding the config option here everywhere, which is not ideal).

PR in io lst here, let's put this on hold until the new version of the source with the other default is out: https://github.com/cta-observatory/ctapipe_io_lst/pull/145

**Comment by FrancaCassol** [comment]
Hi, should we write somewhere the limiting date & run between the old and the new data
(with/without heuristic option) ?

**Comment by moralejo** [comment]
> Hi, should we write somewhere the limiting date & run between the old and the new data (with/without heuristic option) ?

Do we already have something like that in lstchain, in e.g. the calibration?  I thought that would go in lstosa, but it would probably be safer to have it in lstchain (or io_lst) for cases in which one runs without lstosa. The idea would just be to have a different default before a certain run number, right?

**Comment by moralejo** [comment]
I converted to draft, since we may change the switch  to --fatfield-heuristic  . Also to discuss a possible runnumber - dependent default

**Comment by maxnoe** [comment]
I inverted the default now (`--flatfield-heuristic` to use it, off by default)

**Comment by moralejo** [comment]
Thanks @maxnoe. What about the runnumber-dependent automatic default? In order to have it we would need to have the option to set it both ways (i.e. flatfield-heuristic  true or false). Perhaps it is better to do this at the lstosa level, explicitly using the flatfield-heuristic option for the old data?  @morcuended, it should not be too complicated, right? And there must be similar epoch-dependent configurations in lstosa already.

**Comment by morcuended** [comment]
This flatfield heuristic identification would be only for pre-2022 data, right? Right now in lstosa we are simply using a different lstchain configuration for the r0 to dl1 step with that option set to false. This is currently not automated and it would be the first epoch-dependent configuration that we would use in lstosa as far as I know. There are several run-dependent implementations used in calibration scripts for choosing the time calibration and systematics correction files though.

IMO, it would be safer to do this check at lstchain level since it would be reviewed & approved so less prone to errors. With the command line option, we could implement the run-dependent choice in lstosa as well.

**Comment by FrancaCassol** [comment]
Hi, I agree with @morcuended, lstosa is not the only one that is reading the raw data. Ideally the information should be inside the RunSummary (or the future run data base), with a flag that chose the correct type of FF tagging. But, for the moment, should we not put it simply in ctapipe_io_lst?

**Comment by maxnoe** [comment]
Since the rule is pretty simple (Everything from 2022 onwards shouldn't need it) we could just look at `camera_config.date`, right? Or do we want to have a specific run_id?).

The scheme I would propose is having a default of `None` for the option that means "Check the date". This could then be overridden with either False or True to force using or not using the heuristic.

**Comment by FrancaCassol** [comment]
yes, the camera_config.date will be enough I think


> 



> Since the rule is pretty simple (Everything from 2022 onwards shouldn't need it) we could just look at `camera_config.date`, right? Or do we want to have a specific run_id?).

yes, the date will be enough I think

> The scheme I would propose is having a default of `None` for the option that means "Check the date". This could then be overridden with either False or True to force using or not using the heuristic.

yes, it seems to me a good solution. So, if one wants to force an other choice he can do it.

**Comment by maxnoe** [comment]
PR here: https://github.com/cta-observatory/ctapipe_io_lst/pull/146

**Review by FrancaCassol — APPROVED** [review]

**Comment by maxnoe** [comment]
Sorry, wrong keyword, fixed now

**Review by FrancaCassol — APPROVED** [review]

**Pull request merged**
