### PR TITLE
Production scripts onsite

### PR DESCRIPTION
**Pull request by vuillaut**
These are scripts for onsite data reduction.
For now, you can find MC reduction from R0 to DL1 following structure.
These have been tested.
To do:
- [ ] update for real time once PR #201 has been merged
- [ ] update with scripts for DL1 to DL2 (I need to clean what I have)

### CODE REVIEW

**Comment by vuillaut** [comment]
Does someone want to start reviewing?
We can go step by step and add the other scripts in a following PR... 
I'll run last checks to see that everything works as intended.

**Comment by vuillaut** [comment]
> Does someone want to start reviewing? @morcuended @FrancaCassol @rlopezcoto 
> We can go step by step and add the other scripts in a following PR...
> I'll run last checks to see that everything works as intended.

**Comment by rlopezcoto** [comment]
Hi, this is quite a long PR and it would be great if people could test it before it is merged. Is there any argument for the need of these scripts before the next lstchain release? It would be great if they can be tested by @morcuended or any other that will be working with the onsite data handling, but not sure if they are going to have time before tomorrow...

**Comment by vuillaut** [comment]
> Hi, this is quite a long PR and it would be great if people could test it before it is merged. Is there any argument for the need of these scripts before the next lstchain release? It would be great if they can be tested by @morcuended or any other that will be working with the onsite data handling, but not sure if they are going to have time before tomorrow...

Well, I thought the idea was to have all scripts in the next release to have a fixed working chain for the data analysis....

**Comment by morcuended** [comment]
> > Does someone want to start reviewing? @morcuended @FrancaCassol @rlopezcoto
> > We can go step by step and add the other scripts in a following PR...
> > I'll run last checks to see that everything works as intended.
> 
> Hi @vuillaut, @rlopezcoto, I can review but only starting from tomorrow morning

Same here, I'll be able to start checking them tomorrow afternoon.

**Comment by rlopezcoto** [comment]
yes, the idea was to merge as much code as possible for _real data_ onsite analysis, the problem I see is that we will be a bit tight in the schedule. I had a quick look to the PR and it is mainly concentrating on MC and adding features, which give an added value, but at the moment would be to the expense of merging a non-tested code, while the onsite team already have the tools to make the analysis (except #223, to be merged soon).

**Comment by vuillaut** [comment]
> yes, the idea was to merge as much code as possible for _real data_ onsite analysis, the problem I see is that we will be a bit tight in the schedule. I had a quick look to the PR and it is mainly concentrating on MC and adding features, which give an added value, but at the moment would be to the expense of merging a non-tested code, while the onsite team already have the tools to make the analysis (except #223, to be merged soon).

Yes but that's the point, as said previously, I was waiting for #201 (and now #223)  to be merged to update these scripts for real data analysis. **The onsite scripts will be almost identical**, I am working on it.
As you wish but right now it means that we will run non-merged scripts for the analysis onsite.

**Comment by labsaha** [comment]
I am a bit confused about the need for such script as part of lstchain. The data reduction scripts #201 and #222 are important. If one finds some errors in reduced data sometimes later, then the responsibility goes to those scripts (#201 & #222). One can manually run these scripts to produce DL1 files or create another script to run automatically the lst-chain. So any problem related to data reduction is not really related to the later script. I am not sure if this script should be part of the main software (lstchain) or should be kept separated from lstchain.

**Comment by vuillaut** [comment]
> I am a bit confused about the need for such script as part of lstchain. The data reduction scripts #201 and #222 are important. If one finds some errors in reduced data sometimes later, then the responsibility goes to those scripts (#201 & #222). One can manually run these scripts to produce DL1 files or create another script to run automatically the lst-chain. So any problem related to data reduction is not really related to the later script. I am not sure if this script should be part of the main software (lstchain) or should be kept separated from lstchain.

There indeed not **needed** as part of lstchain for most users and at first I meant to develop them separately. But is there actually any reason not to include them?
Having them in the package will allow consistency in the versioning, easier maintenance, possibly running unit tests even on these...

**Comment by labsaha** [comment]
> There indeed not needed as part of lstchain for most users and at first I meant to develop them separately. But is there actually any reason not to include them?
Having them in the package will allow consistency in the versioning, easier maintenance, possibly running unit tests even on these...

I don't have problem with having these scripts part of lstchain. But I hope as a general strategy, we want to keep the main software as clean as possible for easy maintenance. This is  what I understood through earlier discussion. Of course it may change over the course of time.

As far as I understand this script could be very helpful for onsite team. Hence I think then any development by onsite team should also be part of this repo. Is that what one can consider?  We may need to discuss this if Onsite analysis scripts should be part of lstchain.

**Comment by vuillaut** [comment]
Closing this PR for now.

**Pull request closed without merging**
