### PR TITLE
Low level calib drs4 ro to r1

### PR DESCRIPTION
**Pull request by pawel21**
Dear all,

After discuss with @FrancaCassol I've modified code, now after low level corrections code filled R1 container.

Also, I've improved few things:
1. I'm using ```config``` to set offset, pedestal path, telescope id, how many samples in waveform keep.
2. I changed function power law function to ```time_lapse_corr```, now this coefficients coming from curve fitting to dragon test data at temperature 40 degC

### CODE REVIEW

**Comment by rlopezcoto** [comment]
This looks in principle good to me, but maybe @FrancaCassol would like to have a look before merging

**Comment by FrancaCassol** [comment]
Yes, give me time till tomorrow (I think I have some minor comments)

**Comment by FrancaCassol** [comment]
Hi @pawel21,
there are still some little changes:
- please eliminate (config=None, tool=None) in the __init__ function arguments
- for consistency with other modules in this directory (and most of the modules in ctapipe) could you please rename telid as tel_id ? 
- in the calibrate functions  could you fill also the other elements of the R1 containers (trigger_time, trigger_type) coping them from the R0 container (this will be just a reference copy)? 

thanks

**Comment by pawel21** [comment]
@FrancaCassol 

> Hi @pawel21,
> there are still some little changes:
> 
>     * please eliminate (config=None, tool=None) in the **init** function arguments
> 
>     * for consistency with other modules in this directory (and most of the modules in ctapipe) could you please rename telid as tel_id ?
> 
>     * in the calibrate functions  could you fill also the other elements of the R1 containers (trigger_time, trigger_type) coping them from the R0 container (this will be just a reference copy)?
> 
> 
> thanks

Done

**Comment by rlopezcoto** [comment]
@FrancaCassol if you are happy with the changes, I'll merge so you can do the PR of the remaining part of the calibration code.

**Comment by pawel21** [comment]
Dear @rlopezcoto ,

I'm sorry.
I found bug in my code, so now don't merge my code.

**Comment by pawel21** [comment]
Bug fixed,

@FrancaCassol What should contain R1 containers (trigger time, trigger type), I added also event id, should contain something more?

**Comment by FrancaCassol** [comment]
Hi @pawel21,

 trigger time and trigger type are enough, you find the container (R1CameraContainer) in [https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/io/containers.py](https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/io/containers.py)

**Comment by rlopezcoto** [comment]
thanks @pawel21 and @FrancaCassol, I'll merge this as soon as it is approved

**Comment by pawel21** [comment]
Ok,

I've changed code. My code fill only trigger time and trigger type in R1 container.

**Comment by rlopezcoto** [comment]
Hi @FrancaCassol, can you approve the code so I can merge it? Thanks

**Comment by FrancaCassol** [comment]
Hi @rlopezcoto, yes I approve the code, but I don't see how to do it in the interface...

**Comment by vuillaut** [comment]
> Hi @rlopezcoto, yes I approve the code, but I don't see how to do it in the interface...

Hi @FrancaCassol .
Up right, `Review Files` --> `Review changes `

**Comment by FrancaCassol** [comment]
> > Hi @rlopezcoto, yes I approve the code, but I don't see how to do it in the interface...
> 
> Hi @FrancaCassol .
> Up right, `Files changed` --> `Review changes`

Thanks ;-)

**Pull request merged**
