### PR TITLE
Apply calibration

### PR DESCRIPTION
**Pull request by FrancaCassol**
In this PR I propose a first version of the LSTCamerCalibrator class, which create the dl0 calibrated waveform and a dl1 image on the base of an input hdf5 calibration file.

You find in the notebook  apply_calibration.ipynb the way to use it in an event loop:

```
for i, event in enumerate(reader):
    
    # calibrate r0 --> r1        
    r0_calib.calibrate(event)

    # calibrate r1 --> dl1
    dl1_calibrator(event)
```
No waveform reduction is for the moment included, but can be easily added calling a reducer_product (not used for the moment). 
Please let me know if this way of proceeding is ok or we should  have an other approach.
In order to test the notebook one need a low_level and a high_level calibration file, where should we put them? In cta-lstachain-extra?

Finally, I also move to the lstchain a new version of the pedestal and flat-field components, in order to test them better before a PR in ctapipe

### CODE REVIEW

**Comment by vuillaut** [comment]
Hi @FrancaCassol 

> In this PR I propose a first version of the LSTCamerCalibrator class, which create the dl0 calibrated waveform and a dl1 image on the base of an input hdf5 calibration file.
> 
> You find in the notebook apply_calibration.ipynb the way to use it in an event loop:
> 
> ```
> for i, event in enumerate(reader):
>     
>     # calibrate r0 --> r1        
>     r0_calib.calibrate(event)
> 
>     # calibrate r1 --> dl1
>     dl1_calibrator(event)
> ```

I would suggest some consistency here in the way to apply the calibration. And if possible, consistent with ctapipe as well:
- the naming of the calibrator. in one case the name refers to the starting point (r0), in the other case, it refers to the final point (dl1). I don't mind one or the other convention but would prefer to see the same everywhere (note: explicit is better than implicit so maybe `r0_r1_calibrator` and `r1_dl1_calibrator` ?)
- API consistency. In one case you call `.calibrate` method (previous ctapipe way). In the other you call `calibrator(event)` (current way)

As a summary I would suggest for the calibration methods:
```
r0_r1_calibrate(event)
r1_dl1_calibrate(event)
```

> 
> No waveform reduction is for the moment included, but can be easily added calling a reducer_product (not used for the moment).
> Please let me know if this way of proceeding is ok or we should have an other approach.

This is consistent with ctapipe current way of proceeding so I approve the approach.
Can it simply use ctapipe window integrator as input (e.g. `LocalPeakWindowSum`)?

> In order to test the notebook one need a low_level and a high_level calibration file, where should we put them? In cta-lstachain-extra?

I would say yes if size is acceptable (couple of MB).
Do you also need a fits file to calibrate for tests?

> 
> Finally, I also move to the lstchain a new version of the pedestal and flat-field components, in order to test them better before a PR in ctapipe

I'll try to give a more complete review asap.

**Comment by FrancaCassol** [comment]
Hi @vuillaut 
>
> * the naming of the calibrator. in one case the name refers to the starting point (r0), in the other case, it refers to the final point (dl1). I don't mind one or the other convention but would prefer to see the same everywhere (note: explicit is better than implicit so maybe `r0_r1_calibrator` and `r1_dl1_calibrator` ?)

No problem, I will change the name in the notebook (this is just the name of the declared object), perhaps r0_to_r1_ calibrator and r1_to_dl1_calibrator is even better?

> * API consistency. In one case you call `.calibrate` method (previous ctapipe way). In the other you call `calibrator(event)` (current way)

This is how the r0  calibration is implemented in  r0.py , we could indeed conceive to update it, @pawel21 should I do it or do you prefer to do?


> This is consistent with ctapipe current way of proceeding so I approve the approach.
> Can it simply use ctapipe window integrator as input (e.g. `LocalPeakWindowSum`)?

yes, you can use any ctapipe integrator you want, you pass it as argument or as config to the 
class
```

r1_to_dl1_calibrator = LSTCameraCalibrator(calibration_path = "mycalib.hdf5",  image_extractor="LocalPeakWindowSum",
                               config=charge_config)
```

**Comment by rlopezcoto** [comment]
@FrancaCassol for the test files, please include them in:
`cta-lstchain-extra/calib/camera`

it would also be nice if you could include some test modules for these files.

**Comment by FrancaCassol** [comment]
> I'll wait for some test data to test it.
Sorry for my slow reaction. I will try to provide test calibration data for tomorrow. Only, the r0 data files (the data to be calibrated) are too big for the moment, they must be search by the user (I still didn't menage to get a small data sample, let's try  to relaunch the request ...)

**Comment by vuillaut** [comment]
> > I'll wait for some test data to test it.
> > Sorry for my slow reaction. I will try to provide test calibration data for tomorrow. Only, the r0 data files (the data to be calibrated) are too big for the moment, they must be search by the user (I still didn't menage to get a small data sample, let's try  to relaunch the request ...)

If you can point me where to find the data it's also fine.

**Comment by FrancaCassol** [comment]
Hi @vuillaut,

I just added the path of the data in /fefs and PR in lstachain-extra the calibration files.

**Comment by FrancaCassol** [comment]
Hi all,
what about this PR?

**Comment by rlopezcoto** [comment]
Hi @FrancaCassol, the branch has now conflicts, could you please solve them so we can finish the review and merge it?

**Comment by FrancaCassol** [comment]
Hi @rlopezcoto,
is it ok now?

**Comment by rlopezcoto** [comment]
Hi,
yes, thanks! @vuillaut wanted to perform some tests with the files you uploaded to cta-lstchain-extra, otherwise I'll merge it

**Comment by vuillaut** [comment]
Hi @FrancaCassol,
Sorry but I couldn't manage to make the code working. I am probably not using the right files to test it. If you are available by email, or even better on slack, I'd appreciate some indication/help.

**Comment by rlopezcoto** [comment]
Discussing with @FrancaCassol she confirmed that it is working for her. Since the code is ok, I'll merge it so she can continue with the developments and test it with new files

**Comment by vuillaut** [comment]
Ok. If you have a couple of minutes to help me @FrancaCassol, I'd still like to get this working on my side ;-)

**Comment by FrancaCassol** [comment]
Yes @vuillaut, no problem, do you want that we skype?

**Comment by vuillaut** [comment]
> Yes @vuillaut, no problem, do you want that we skype?

That'd great.
I'll get in touch with skype. Thanks.

**Pull request merged**
