### PR TITLE
Refactor command line arguments of scripts

### PR DESCRIPTION
**Pull request by maxnoe**
* Remove strtobool from distutils,
  use action='store_true', action='store_false' instead.

* Changes default of pedestal cleaning in dl1ab to true, use
  `--no-pedestal-cleaning` to disable

### CODE REVIEW

**Comment by rlopezcoto** [comment]
apart from tests not passing at the moment:

> * Remove strtobool from distutils,
>   use action='store_true', action='store_false' instead.

why did we need to remove `strtobool` to implement a custom solution?

> * Changes default of pedestal cleaning in dl1ab to true, use
>   `--no-pedestal-cleaning` to disable

also, the change of the default of the pedestal cleaning may affect data processing, is this ok for LSTOSA @morcuended ?

**Comment by maxnoe** [comment]
> also, the change of the default of the pedestal cleaning may affect data processing, is this ok for LSTOSA @morcuended ?

This was discussed during the analysis school, and I had the impression that this was uncontroversial

**Comment by maxnoe** [comment]
> why did we need to remove strtobool to implement a custom solution?

I don't understand the question.

**Comment by rlopezcoto** [comment]
> The reason to remove `strtobool` is that `distutils` is deprecated and will be removed.

ok, thanks for clarifying!

**Comment by maxnoe** [comment]
@morcuended @vuillaut @garciagenrique  This changes a couple of command line flags that would need adaption in anything that calls these scripts, e.g. osa and lstmcpipe

**Comment by morcuended** [comment]
Noted

**Review by rlopezcoto — APPROVED** [review]

**Pull request merged**
