### PR TITLE
Fix width and length values in data check plots

### PR DESCRIPTION
**Pull request by moralejo**

### CODE REVIEW

**Comment by morcuended** [comment]
@moralejo is the notebook `notebooks/proton_mc_vs_data.ipynb` intended to be uploaded to the repository?

**Comment by moralejo** [comment]
> @moralejo is the notebook `notebooks/proton_mc_vs_data.ipynb` intended to be uploaded to the repository?

yes...  it's been there for a while. Since I use it to do some comparisons I presented and discussed a couple of time I think it should be public.

**Comment by moralejo** [comment]
Ah wait... you mean why in this PR?

**Comment by morcuended** [comment]
Yes, I meant both, because it seemed unrelated. But it's OK with me.

**Comment by moralejo** [comment]
> Ah wait... you mean why in this PR?

no good reason, I guess!

**Comment by moralejo** [comment]
I prefer to leave it here, even if it is unrelated. I am afraid I could mess something up if I try to fix this.
Can you approve it?

**Review by morcuended — APPROVED** [review]
Just wanted to make sure about the notebook.

**Comment by moralejo** [comment]
> Just wanted to make sure about the notebook.

In the end I removed it. This made your review obsolete I think.

**Review by morcuended — APPROVED** [review]

**Pull request merged**
