### PR TITLE
Imput pointing values with linear interpolation

### LINKED ISSUE #285: Error in dl1 to dl2 step when pointing info is missing
Sometimes UCTS timestamp is missing in the latest runs, hence pointing coordinates cannot be interpolated nor added to the data stream. In these cases, `alt_tel` and `az_tel` are set to `NaN`. Later on, when running `lstchain_mc_dl1_to_dl2.py` over those runs with missing pointing info I get this error:
```
Traceback (most recent call last):
  File "/home/daniel.morcuende/software/cta-lstchain/cta-lstchain/lstchain/scripts/lstchain_mc_dl1_to_dl2.py", line 89, in <module>
    main()
  File "/home/daniel.morcuende/software/cta-lstchain/cta-lstchain/lstchain/scripts/lstchain_mc_dl1_to_dl2.py", line 79, in main
    dl2 = dl1_to_dl2.apply_models(data, cls_gh, reg_energy, reg_disp_vector, custom_config=config)
  File "/fefs/home/daniel.morcuende/software/cta-lstchain/cta-lstchain/lstchain/reco/dl1_to_dl2.py", line 396, in apply_models
    alt_tel = dl2['alt_tel'].values
  File "/home/daniel.morcuende/.conda/envs/mycta/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/daniel.morcuende/.conda/envs/mycta/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'alt_tel'
```
How can we overcome this? Should we throw away those problematic events in this second step by checking first whether dl2['alt_tel'].values are NaN?
Any suggestion?

### PR DESCRIPTION
**Pull request by vuillaut**
This PR should fix #285 
- the default value of `nan` instead of None should ensure that the columns exist even when a calculation fails
- I propose a linear interpolation between pointing values when they are missing with the hypothesis that events are in order and come at regular rate

### CODE REVIEW

**Comment by morcuended** [comment]
Thanks a lot, @vuillaut. I'm testing the changes right now. I will get back to you asap.

**Comment by vuillaut** [comment]
Note that if a lot of values are missing, it might not be the best approach and feedback is welcome.

**Comment by morcuended** [comment]
Sorry for late notice. I got this error when running the ro to dl1 scripts:
```
Traceback (most recent call last):
  File "/home/daniel.morcuende/software/to_remove/cta-lstchain/lstchain/scripts/lstchain_data_r0_to_dl1.py", line 78, in <module>
    main()
  File "/home/daniel.morcuende/software/to_remove/cta-lstchain/lstchain/scripts/lstchain_data_r0_to_dl1.py", line 73, in main
    pointing_file_path=args.pointing_file_path
  File "/fefs/home/daniel.morcuende/software/to_remove/cta-lstchain/lstchain/reco/dl0_to_dl1.py", line 377, in r0_to_dl1
    containers=[dl1_container, extra_im])
  File "/home/daniel.morcuende/.local/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 279, in write
    self._append_row(table_name, containers)
  File "/home/daniel.morcuende/.local/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 255, in _append_row
    row[colname] = value
  File "tables/tableextension.pyx", line 1595, in tables.tableextension.Row.__setitem__
TypeError: invalid type (<class 'astropy.units.quantity.Quantity'>) for column ``alt_tel``
```

**Comment by vuillaut** [comment]
@morcuended 
I messed up with two PR and my git history.
I close this one and opened #295.
I tested on a buggy file and it should work now but please double check if you can.

**Pull request closed without merging**
