### PR TITLE
Fix tests for ctapipe_0.17 branch

### PR DESCRIPTION
**Pull request by chaimain**
Forwarded from #1106 to have proper commit for the exact change. This will help solve some failing tests in #1054

### CODE REVIEW

**Comment by FrancaCassol** [comment]
Hi @chaimain, @maxnoe for solving the problem with the fit intensity scan one has to update the calibration files in the test_data adding. I do not know how to upload them, you find the correct ones in:
/fefs/aswg/workspace/franca.cassol/software/cta-lstchain/test_data/real/monitoring/PixelCalibration/Cat-A/calibration/20221001/ctapipe-v0.17/

**Comment by maxnoe** [comment]
I uploaded the new test files and update the path so that the tests use the new files, locally it worked already

**Comment by gabemery** [comment]
Do we want to fix the codacy issue in this PR too?
https://app.codacy.com/gh/cta-observatory/cta-lstchain/file/89587946300/issues/source?fileBranchId=32508679

(Unused line in the script create_test_calibration_files.sh)

**Comment by chaimain** [comment]
I think the conflict issue of `ctapipe_0.17` branch with `master` is separate from tests, and can be managed separately on that branch itself maybe. @FrancaCassol can you check it after we merge this?

**Review by maxnoe — APPROVED** [review]

**Comment by FrancaCassol** [comment]
> I think the conflict issue of `ctapipe_0.17` branch with `master` is separate from tests, and can be managed separately on that branch itself maybe. @FrancaCassol can you check it after we merge this?

Hi @chaimain, I am not sure to understand what you ask to test, could please recall it to me?

**Comment by chaimain** [comment]
> > I think the conflict issue of `ctapipe_0.17` branch with `master` is separate from tests, and can be managed separately on that branch itself maybe. @FrancaCassol can you check it after we merge this?
> 
> Hi @chaimain, I am not sure to understand what you ask to test, could please recall it to me?

There were some conflicts in `ctapipe_0.17` branch after your last PR #1071 was merged to `master`, and @maxnoe tried to address them https://github.com/cta-observatory/cta-lstchain/pull/1054#issuecomment-1558987761. Can you confirm whether everything is ok with the changes he made to those specific files?

**Pull request merged**
