### PR TITLE
test ctapipe v0.15

### PR DESCRIPTION
**Pull request by vuillaut**

### CODE REVIEW

**Comment by maxnoe** [comment]
Ctapipe 0.15 is python 3.8+, you should switch the CI to use 3.8 and 3.9 (possibly 3.10)

**Comment by vuillaut** [comment]
> Ctapipe 0.15 is python 3.8+, you should switch the CI to use 3.8 and 3.9 (possibly 3.10)

while doing so, I saw that comment:
```
        # we currently only support python 3.7 since traitlets 5 requires 3.7
        # and protozfits does not support python 3.8.
 ```

But we were already working with python v3.8... ?

**Comment by maxnoe** [comment]
@vuillaut that comment is outdated, protozfits is now build by conda-forge for all python versions supported by conda-forge:

https://anaconda.org/conda-forge/protozfits/files

**Comment by maxnoe** [comment]
We will also need an update to `ctapipe_io_lst` for 0.15 (or at least relaxing the astropy 4.2 requirement).

**Comment by vuillaut** [comment]
> We will also need an update to `ctapipe_io_lst` for 0.15 (or at least relaxing the astropy 4.2 requirement).

Yes I can see.
Do you know if that requirement is a strong one or if it could simply be relaxed  to `>=4.2`?

**Comment by maxnoe** [comment]
@vuillaut Let's try... I don't remember if there was any strong reason other then the same requirement in ctapipe

**Comment by maxnoe** [comment]
@vuillaut ctapipe 0.15 (0.13 actually) also requires bokeh >= 2.0 along with changes to the bokeh-based `CameraDisplay`, which I think will make changes necessary in code that is not well covered by unit tests* (dl1 datacheck etc.) 

* Looking if plots still look like expected is kind of hard in unit tests

**Comment by vuillaut** [comment]
> We will also need an update to `ctapipe_io_lst` for 0.15 (or at least relaxing the astropy 4.2 requirement).

For the record:
https://github.com/cta-observatory/ctapipe_io_lst/pull/153

**Comment by garciagenrique** [comment]
> @vuillaut ctapipe 0.15 (0.13 actually) also requires bokeh >= 2.0 along with changes to the bokeh-based `CameraDisplay`, which I think will make changes necessary in code that is not well covered by unit tests* (dl1 datacheck etc.)
> 
> `*` Looking if plots still look like expected is kind of hard in unit tests

Should making the checks by hand and comparing outputs using the two bokeh versions will help ? @maxnoe @moralejo 
I can take care of this checks to speed up the PR

**Comment by moralejo** [comment]
> > @vuillaut ctapipe 0.15 (0.13 actually) also requires bokeh >= 2.0 along with changes to the bokeh-based `CameraDisplay`, which I think will make changes necessary in code that is not well covered by unit tests* (dl1 datacheck etc.)
> > `*` Looking if plots still look like expected is kind of hard in unit tests
> 
> Should making the checks by hand and comparing outputs using the two bokeh versions will help ? @maxnoe @moralejo I can take care of this checks to speed up the PR

I think so, very likely if there are problems they will be of the catastrophic type... easy to spot. Would be great if you can have a look!

**Comment by rlopezcoto** [comment]
Superseded by #1053

**Pull request closed without merging**
