### PR TITLE
Fix azimuth & RA range

### PR DESCRIPTION
**Pull request by moralejo**
Fixed wrong range of RA and telescope azimuth in datacheck plots (was -pi, pi, now is 0, 2pi)

### CODE REVIEW

**Review by maxnoe — CHANGES_REQUESTED** [review]
Use `astropy.coordinates.Angle.wrap_at` to get a known range for input angles, e.g.:
```

In [1]: from astropy.coordinates import Angle
   ...: import astropy.units as u
   ...: import numpy as np
   ...: Angle(np.arange(-360, 361, 90) * u.deg).wrap_at(180 * u.deg)  # or 360 * u.deg
Out[1]: <Angle [   0.,   90., -180.,  -90.,    0.,   90., -180.,  -90.,    0.] deg>

In [2]: 
   ...: Angle(np.arange(-360, 361, 90) * u.deg).wrap_at(360 * u.deg)  # or 360 * u.deg
Out[2]: <Angle [  0.,  90., 180., 270.,   0.,  90., 180., 270.,   0.] deg>
```

**Comment by moralejo** [comment]
> Use `astropy.coordinates.Angle.wrap_at` to get a known range for input angles, e.g.:
> 
> ```
> 
> In [1]: from astropy.coordinates import Angle
>    ...: import astropy.units as u
>    ...: import numpy as np
>    ...: Angle(np.arange(-360, 361, 90) * u.deg).wrap_at(180 * u.deg)
> Out[1]: <Angle [   0.,   90., -180.,  -90.,    0.,   90., -180.,  -90.,    0.] deg>
> 

The angles in question are not astropy quantities, so the code would become unnecessarily clumsy I think.

**Comment by maxnoe** [comment]
`Angle(mean_ra, u.rad).wrap_at('360d').rad`

**Review by morcuended — APPROVED** [review]

**Review by maxnoe — APPROVED** [review]
Why ra in deg and az in rad?

**Comment by moralejo** [comment]
> Why ra in deg and az in rad?

For the telescope az, alt I just kept radians because this is what we have in the DL1 files for the event-wise values, no other reason. I show them in degrees in the plots, though.

**Pull request merged**
