### PR TITLE
Remove jinja pin

### PR DESCRIPTION
**Pull request by maxnoe**
Should not be needed anymore and fixes a dependabot alert

### CODE REVIEW

**Review by morcuended — DISMISSED** [review]

**Comment by maxnoe** [comment]
There are scheduled maintenance downtimes today at in2p3, where the dataserver of the ctapipe test data is hosted, that's why the tests keep failing with connection issues

**Review by morcuended — APPROVED** [review]
CI fail is unrelated (due to non deterministic test of the IRF scaling factor)

**Comment by morcuended** [comment]
I think this can be merged already

**Comment by rlopezcoto** [comment]
one of the tests was giving troubles, I am re-running it now...

**Comment by morcuended** [comment]
After merging #1300, I hope this test will not cause problems anymore.

**Review by morcuended — APPROVED** [review]

**Comment by morcuended** [comment]
this can be merged

**Pull request merged**
