### PR TITLE
Installation package

### PR DESCRIPTION
**Pull request by vuillaut**
Hi.
Here is another refactoring.
I have reorganised the repository for clarity and to make a package out of it:
- scripts and functions are now separated
- functions are now part of a package 'lstchain'
- refactoring of files into submodules: calib, reco, visualization, io, magic-lst
- installation procedure with python setup.py install
- unit test for imports and the main pipeline steps: `d0_to_dl1`,`buildModels`, `ApplyModels`
- add imports in notebooks

After installation, one can now do
`from lstchain.reco import ...  `
It will prevent a lot of issues with relatives paths import.

The unit tests I set-up are really simple and not meant to check results but to ensure the pipeline is running. This way we can have a continuous integration and be sure future modification won't impact running the pipeline.

ps: this PR should probably come after #30

### CODE REVIEW

**Comment by rlopezcoto** [comment]
thanks @vuillaut, that's a hell of a refactoring...
my obvious first question is: does this break any of the code/notebooks @misabelber has been including for the bootcamp? 
Did you perform any tests to check that you do not get errors when running them?
As I said before, some test modules would be very helpful to test that code is still running after performing these changes.
If this gets finished before next week, we might consider an introduction of the cta-lstchain repo for the next week in the bootcamp, @vuillaut, @misabelber would you be up to it?

**Comment by vuillaut** [comment]
Hi
I checked that all the notebook are running and giving consistent results, as well as the main functions. I used the refactoring tools from pycharm that help a lot doing the job and avoiding mistakes. 
I cannot guarantee 100% I have not missed something but the bulk of the scripts/functions are running as before.

**Comment by vuillaut** [comment]
- Removed requirement.txt and replaced with environment.yml
- Added .travis.yml
- Updated README with an installation procedure

Travis can now been used for CI (working on my fork).

**Comment by vuillaut** [comment]
Hi @rlopezcoto 
May I ask where we are with this PR?
I think @misabelber tested the code, right?
Thanks.

**Comment by rlopezcoto** [comment]
Yes, and this PR can be merged already as far as it is reported in #34 that everything runs smoothly.

**Comment by vuillaut** [comment]
Thanks @rlopezcoto !
So now you should be able to set-up travis to do the CI for this repo, ensuring that future PR do not break everything (more unit tests should be added also).
Sorry I can't do it myself since I don't have the rights on the repo.

**Comment by rlopezcoto** [comment]
I have admin permission but I am not the owner of the repo, so I believe that we need @kosack to set up travis for us

**Comment by rlopezcoto** [comment]
Hi @kosack, since you are the owner of the cta-lstchain repo, it seems you are the only one able to set up travis, could you please do that or give also owner permissions to myself or @moralejo? Thanks

**Pull request merged**
