### PR TITLE
Add meaningful signed parameters to DL2

### PR DESCRIPTION
**Pull request by moralejo**
Calculate appropriate signs for skewness and time_gradient, referred to the reconstructed source position.

### CODE REVIEW

**Comment by moralejo** [comment]
Ah damn... we need those before, for training. Back to draft.

**Comment by moralejo** [comment]
But other quantities reconstructed in the dl1 => dl2 step like reco_disp_norm are used in the g/h separation RF, so it should be possible to use also these signed_time_gradient and signed_skewness

**Review by rlopezcoto — COMMENTED** [review]
Apart from the pep8 formatting (space between mathematical operators and variables), it looks good

**Review by rlopezcoto — DISMISSED** [review]

**Comment by moralejo** [comment]
I realized that we can use ctapipe's camera_to_shower_coordinates (as Seiya does for source-dep analysis) instead of creating a new function. Results are identical, will do.

**Review by rlopezcoto — APPROVED** [review]

**Pull request merged**
