### PR TITLE
Fix bare excepts

### PR DESCRIPTION
**Pull request by misabelber**
Hi!
I tried to solve issue #93 and set a certain error in the bare excepts. I don't have a lot of experience in error handling in Python so I'm not completely sure if I used the proper error type. If anyone can take a look and see if seems correct, I will be thankful.

### CODE REVIEW

**Comment by misabelber** [comment]
I don't know why for some reason commits from PR #98 are appearing here :s

**Comment by rlopezcoto** [comment]
Thanks @misabelber. @dneise could you please have a look at the correction?
Regarding the appearing of #98 commits... maybe you picked the upstream branch and merge it with your master before creating fix-excepts?

**Comment by misabelber** [comment]
Probably yes, and now I don't know how to fix it...

**Comment by rlopezcoto** [comment]
Since there is only one real change, probably the easiest would be to close this PR, stash all the changes and merge it with the upstream/master. Not sure if the order I'm putting here is correct but should be something like:

`git stash drop`
`git fetch upstream`
`git reset --hard upstream/master`
`git push --force`

and then you can add your changes. If you manage to have your branch even with cta-lstchain, it should be solved and you can commit the new changes and cancel this PR.

**Comment by misabelber** [comment]
Ok! I'll try it

**Pull request closed without merging**
