### PR TITLE
Remove obsolete sensitivity function

### PR DESCRIPTION
**Pull request by moralejo**
Fixed sensitivity formula (it seems it is not used anywhere, but just in case)

### CODE REVIEW

**Review by rlopezcoto — DISMISSED** [review]

**Comment by rlopezcoto** [comment]
tests are not passing after this modification, we need to change the values tested as well

**Comment by moralejo** [comment]
> tests are not passing after this modification, we need to change the values tested as well

Sorry for that, let's just remove it, no?

**Comment by maxnoe** [comment]
Do we still need the other function right above?

**Comment by moralejo** [comment]
I would not remove it (in this PR at least), since that one is correct.

**Comment by maxnoe** [comment]
But for what is it needed when we can just use https://github.com/cta-observatory/pyirf/blob/285bca156d9c7d88dbfe7a5af402fde7321924fb/pyirf/sensitivity.py#L95 ?

**Comment by moralejo** [comment]
@rlopez perhaps you still use those functions somewhere? From my side I have no objection to drop them.

**Comment by rlopezcoto** [comment]
> @rlopezcoto perhaps you still use those functions somewhere? From my side I have no objection to drop them.

no, I was not using them, maybe @misabelber, otherwise I think it should be fine to remove them and update any offline code to work with `pyirf` functions that are being better maintained.

**Review by rlopezcoto — APPROVED** [review]

**Comment by moralejo** [comment]
Ok, let's merge it like this to remove the buggy formula. @misabelber, can check whether the other functions (or the whole file) superseded by pyirf can be removed, and of so do it in a separate PR?

**Comment by misabelber** [comment]
I think the whole file can be removed, I am not using it for anything right now, as said, it has been superseded by pyirf.

**Pull request merged**
