### PR TITLE
Fix pandas unit issue and reenable tests on python 3.8, fixes #723

### LINKED ISSUE #723: Tests failing with a fresh lstchain instalation
Just reported by Mónica Vázquez, tests are not passing with a fresh lstchain installation, first only run with private data:

```
pytest -m private_data -v lstchain
```

```python
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/dmorcuende/.local/miniconda3/envs/lst/bin/python
cachedir: .pytest_cache
rootdir: /home/dmorcuende/software/lst/cta-lstchain
plugins: ordering-0.6
collected 133 items / 117 deselected / 16 selected                                                                                                                                                                                                                             

lstchain/irf/tests/test_hdus.py::test_create_event_list PASSED                                                                                                                                                                                                           [  6%]
lstchain/irf/tests/test_hdus.py::test_create_obs_hdu_index PASSED                                                                                                                                                                                                        [ 12%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_lstchain_data_r0_to_dl1 PASSED                                                                                                                                                                                     [ 18%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_observed_dl1_validity PASSED                                                                                                                                                                                       [ 25%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_lstchain_merge_dl1_hdf5_observed_files PASSED                                                                                                                                                                      [ 31%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_merge_datacheck_files PASSED                                                                                                                                                                                       [ 37%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_lstchain_observed_dl1_to_dl2 PASSED                                                                                                                                                                                [ 43%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_observed_dl1ab PASSED                                                                                                                                                                                              [ 50%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_read_data_dl2_to_QTable PASSED                                                                                                                                                                                     [ 56%]
lstchain/scripts/tests/test_lstchain_scripts.py::test_run_summary PASSED                                                                                                                                                                                                 [ 62%]
lstchain/tests/test_lstchain.py::test_r0_to_dl1_observed PASSED                                                                                                                                                                                                          [ 68%]
lstchain/tests/test_lstchain.py::test_r0_available PASSED                                                                                                                                                                                                                [ 75%]
lstchain/tools/tests/test_tools.py::test_create_dl3 FAILED                                                                                                                                                                                                               [ 81%]
lstchain/tools/tests/test_tools.py::test_index_dl3_files PASSED                                                                                                                                                                                                          [ 87%]
lstchain/visualization/tests/test_plot_calib.py::test_plot_calib PASSED                                                                                                                                                                                                  [ 93%]
lstchain/visualization/tests/test_plot_drs4.py::test_plot_drs4 PASSED                                                                                                                                                                                                    [100%]

=================================================================================================================================== FAILURES ===================================================================================================================================
_______________________________________________________________________________________________________________________________ test_create_dl3 ________________________________________________________________________________________________________________________________

temp_dir_observed_files = PosixPath('/tmp/test_lstchainbrom6kh9'), observed_dl2_file = PosixPath('/tmp/test_lstchainbrom6kh9/dl2_LST-1.Run02008.0000.h5')

    @pytest.mark.private_data
    @pytest.mark.run(after="test_create_irf")
    def test_create_dl3(temp_dir_observed_files, observed_dl2_file):
        """
        Generating an DL3 file from a test DL2 files and test IRF file
        """
        from lstchain.tools.lstchain_create_dl3_file import DataReductionFITSWriter
    
        irf_file = temp_dir_observed_files / "irf.fits.gz"
        config_file = os.path.join(os.getcwd(), "docs/examples/dl3_tool_config.json")
    
>       assert (
            run_tool(
                DataReductionFITSWriter(),
                argv=[
                    f"--input-dl2={observed_dl2_file}",
                    f"--output-dl3-path={temp_dir_observed_files}",
                    f"--input-irf={irf_file}",
                    "--source-name=Crab",
                    "--source-ra=83.633deg",
                    "--source-dec=22.01deg",
                    "--overwrite",
                ],
                cwd=temp_dir_observed_files,
            )
            == 0
        )
E       assert 1 == 0
E         +1
E         -0

lstchain/tools/tests/test_tools.py:73: AssertionError
----------------------------------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------------------------------
2021-07-16 14:15:48,285 CRITICAL [ctapipe.DataReductionFITSWriter] (application.inner): Bad config encountered during initialization: Path "/tmp/test_lstchainbrom6kh9/irf.fits.gz" does not exist
=============================================================================================================================== warnings summary ===============================================================================================================================
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/tables/__init__.py:24
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/tables/__init__.py:24
  /home/dmorcuende/.local/miniconda3/envs/lst/lib/python3.7/site-packages/tables/__init__.py:24: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
    from .utilsextension import (

lstchain/io/io.py:300
  /home/dmorcuende/software/lst/cta-lstchain/lstchain/io/io.py:300: DeprecationWarning: invalid escape sequence \_
    log.exception(f"{filename} cannot be smart merged '¯\_(ツ)_/¯'")

../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/h5py/__init__.py:46
  /home/dmorcuende/.local/miniconda3/envs/lst/lib/python3.7/site-packages/h5py/__init__.py:46: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
    from ._conv import register_converters as _register_converters

../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/regions/_geometry/__init__.py:8
  /home/dmorcuende/.local/miniconda3/envs/lst/lib/python3.7/site-packages/regions/_geometry/__init__.py:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    from .polygonal_overlap import *

lstchain/tests/test_lstchain.py::test_r0_to_dl1_observed
lstchain/tests/test_lstchain.py::test_r0_to_dl1_observed
  /home/dmorcuende/.local/miniconda3/envs/lst/lib/python3.7/site-packages/tables/array.py:241: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    (oid, self.atom, self.shape, self._v_chunkshape) = self._open_array()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================================================================================== short test summary info ============================================================================================================================
FAILED lstchain/tools/tests/test_tools.py::test_create_dl3 - assert 1 == 0
===================================================================================================== 1 failed, 15 passed, 117 deselected, 7 warnings in 294.00s (0:04:53) =====================================================================================================

```

Then tried all test `pytest -m 'private_data or not private_data' -v lstchain
` and this time the only test failing was `lstchain/mc/tests/test_senstivity.py::test_sensitivity FAILED`

```
lstchain/mc/tests/test_senstivity.py:151: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lstchain/mc/sensitivity.py:620: in sensitivity_gamma_efficiency
    events_bin_g = events_g[(e_reco_g < energy[i+1]) & (e_reco_g > energy[i])]
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/frame.py:3446: in __getitem__
    return self._getitem_bool_array(key)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/frame.py:3501: in _getitem_bool_array
    return self._take_with_is_copy(indexer, axis=0)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/generic.py:3625: in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/generic.py:3610: in take
    self._consolidate_inplace()
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/generic.py:5556: in _consolidate_inplace
    self._protect_consolidate(f)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/generic.py:5544: in _protect_consolidate
    result = f()
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/generic.py:5554: in f
    self._mgr = self._mgr.consolidate()
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/internals/managers.py:612: in consolidate
    bm._consolidate_inplace()
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/internals/managers.py:617: in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/internals/managers.py:1968: in _consolidate
    list(group_blocks), dtype=dtype, can_consolidate=_can_consolidate
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/pandas/core/internals/managers.py:1994: in _merge_blocks
    new_values = np.vstack([b.values for b in blocks])  # type: ignore[misc]
<__array_function__ internals>:6: in vstack
    ???
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity.py:1512: in __array_function__
    return super().__array_function__(function, types, args, kwargs)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/numpy/core/shape_base.py:282: in vstack
    return _nx.concatenate(arrs, 0)
<__array_function__ internals>:6: in concatenate
    ???
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity.py:1517: in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity_helper/function_helpers.py:372: in concatenate
    arrays, kwargs, unit, out = _iterable_helper(*arrays, out=out, axis=axis)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity_helper/function_helpers.py:364: in _iterable_helper
    arrays, unit = _quantities2arrays(*args)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity_helper/function_helpers.py:345: in _quantities2arrays
    arrays = tuple((q._to_own_unit(arg)) for arg in args)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity_helper/function_helpers.py:345: in <genexpr>
    arrays = tuple((q._to_own_unit(arg)) for arg in args)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity.py:1354: in _to_own_unit
    _value = as_quantity.to_value(self.unit)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity.py:743: in to_value
    value = self._to_value(unit, equivalencies)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/quantity.py:663: in _to_value
    equivalencies=equivalencies)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/core.py:987: in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/core.py:918: in _get_converter
    raise exc
../../../.local/miniconda3/envs/lst/lib/python3.7/site-packages/astropy/units/core.py:904: in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
```
```
=========================================================================================================================== short test summary info ============================================================================================================================
FAILED lstchain/mc/tests/test_senstivity.py::test_sensitivity - astropy.units.core.UnitConversionError: '' (dimensionless) and 'deg2' (solid angle) are not convertible

```

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by maxnoe** [comment]
Pandas 1.2:

```

In [1]: import pandas as pd

In [2]: import astropy.units as u

In [3]: df = pd.DataFrame()

In [4]: df['theta2'] = [0, 0.2, 0.3] * u.deg**2

In [5]: df
Out[5]: 
   theta2
0     0.0
1     0.2
2     0.3
```


Pandas 1.3:

```
In [1]: import pandas as pd

In [2]: import astropy.units as u

In [3]: df = pd.DataFrame()

In [4]: df['theta2'] = [0, 0.2, 0.3] * u.deg**2

In [5]: df
Out[5]: ---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/core/frame.py in __repr__(self)
   1000             line_width=width,
   1001             max_colwidth=max_colwidth,
-> 1002             show_dimensions=show_dimensions,
   1003         )
   1004 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/core/frame.py in to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, max_rows, min_rows, max_cols, show_dimensions, decimal, line_width, max_colwidth, encoding)
   1132                 buf=buf,
   1133                 encoding=encoding,
-> 1134                 line_width=line_width,
   1135             )
   1136 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in to_string(self, buf, encoding, line_width)
   1051 
   1052         string_formatter = StringFormatter(self.fmt, line_width=line_width)
-> 1053         string = string_formatter.to_string()
   1054         return save_to_buffer(string, buf=buf, encoding=encoding)
   1055 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/string.py in to_string(self)
     23 
     24     def to_string(self) -> str:
---> 25         text = self._get_string_representation()
     26         if self.fmt.should_show_dimensions:
     27             text = "".join([text, self.fmt.dimensions_info])

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/string.py in _get_string_representation(self)
     38             return self._empty_info_line
     39 
---> 40         strcols = self._get_strcols()
     41 
     42         if self.line_width is None:

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/string.py in _get_strcols(self)
     29 
     30     def _get_strcols(self) -> list[list[str]]:
---> 31         strcols = self.fmt.get_strcols()
     32         if self.fmt.is_truncated:
     33             strcols = self._insert_dot_separators(strcols)

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in get_strcols(self)
    538         Render a DataFrame to a list of columns (as lists of strings).
    539         """
--> 540         strcols = self._get_strcols_without_index()
    541 
    542         if self.index:

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in _get_strcols_without_index(self)
    802                 int(self.col_space.get(c, 0)), *(self.adj.len(x) for x in cheader)
    803             )
--> 804             fmt_values = self.format_col(i)
    805             fmt_values = _make_fixed_width(
    806                 fmt_values, self.justify, minimum=header_colwidth, adj=self.adj

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in format_col(self, i)
    823             space=self.col_space.get(frame.columns[i]),
    824             decimal=self.decimal,
--> 825             leading_space=self.index,
    826         )
    827 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in format_array(values, formatter, float_format, na_rep, digits, space, justify, decimal, leading_space, quoting)
   1238     )
   1239 
-> 1240     return fmt_obj.get_result()
   1241 
   1242 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in get_result(self)
   1269 
   1270     def get_result(self) -> list[str]:
-> 1271         fmt_values = self._format_strings()
   1272         return _make_fixed_width(fmt_values, self.justify)
   1273 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in _format_strings(self)
   1516 
   1517     def _format_strings(self) -> list[str]:
-> 1518         return list(self.get_result_as_array())
   1519 
   1520 

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/pandas/io/formats/format.py in get_result_as_array(self)
   1500             # large values: more that 8 characters including decimal symbol
   1501             # and first digit, hence > 1e6
-> 1502             has_large_values = (abs_vals > 1e6).any()
   1503             has_small_values = (
   1504                 (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/astropy/units/quantity.py in __array_ufunc__(self, function, method, *inputs, **kwargs)
    457         # consistent units between two inputs (e.g., in np.add) --
    458         # and the unit of the result (or tuple of units for nout > 1).
--> 459         converters, unit = converters_and_unit(function, method, *inputs)
    460 
    461         out = kwargs.get('out', None)

~/.local/anaconda/envs/cta-dev/lib/python3.7/site-packages/astropy/units/quantity_helper/converters.py in converters_and_unit(function, method, *args)
    187                             "argument is not a quantity (unless the "
    188                             "latter is all zero/infinity/nan)"
--> 189                             .format(function.__name__))
    190             except TypeError:
    191                 # _can_have_arbitrary_unit failed: arg could not be compared

UnitConversionError: Can only apply 'greater' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```

**Comment by monicava** [comment]
pytest -m 'private_data or not private_data' -v lstchain 
passes BUT

pytest -m private_data -v lstchain
**still gives the same error:**
lstchain/tools/tests/test_tools.py::test_create_dl3 FAILED                                                                            [ 81%]

**Comment by maxnoe** [comment]
@monicava That seems to mean that that test depends on another test to be executed (e.g. processing a mc file to produce the IRFs maybe?)

We should set this up properly using fixtures in that case.

**Comment by morcuended** [comment]
https://github.com/cta-observatory/cta-lstchain/blob/5032edb033a3d01bc6db45b930ad62d2df3a302a/lstchain/tools/tests/test_tools.py#L62-L70

Here the IRFs file should be passed as fixture. This test is expected to run after `test_create_irf` though.

**Comment by maxnoe** [comment]
>  This test is expected to run after test_create_irf though.

I think this pytest order plugin only orders the tests that are supposed to run, not make sure that a test is run. It's not a dependency management system, that's what fixtures are for.

I think we should just remove that ordering plugin, see what breaks and make sure all tests can be run individually by using fixtures.

**Pull request merged**
