### PR TITLE
Fix src dependent

### PR DESCRIPTION
**Pull request by rlopezcoto**
There was a small bug on the `lstchain_dl1_to_dl2.py` script that did not allow to process data using src_dependent analysis. I also got problems with `data_src_dep.set_index('index', drop=True)` why was this line there @SeiyaNozaki?

I also updated the src_dependent input card, that still had some old variables defined.

### CODE REVIEW

**Comment by SeiyaNozaki** [comment]
`index` column was there after adding source-dependent parameters,  so I dropped this column.
I think #381 solved this issue, so now no need to add this line.
Thanks!

**Comment by rlopezcoto** [comment]
>I think #381 solved this issue, so now no need to add this line.

thanks @SeiyaNozaki, I removed the line completely

**Comment by rlopezcoto** [comment]
@SeiyaNozaki then, do you agree with the changes? if yes, could you approve the PR?

**Comment by SeiyaNozaki** [comment]
yes, please! :)

**Pull request merged**
