### PR TITLE
Adding hillas uncertainties fields to lstcontainers and ro_to_dl1 script

### PR DESCRIPTION
**Pull request by andres-baquero**
Here I add the fields for width and length uncertainties already calculated by ctapipe

### CODE REVIEW

**Comment by maxnoe** [comment]
The diff looks much larger and you have conflicts. Please make sure you start your new branch from the current master branch. Also note, that due to the use of private test data, the CI system will not work for PRs from a fork.

I will add you yo the lst-dev team, then you need to do a fresh clone of this repository (not your fork!), create the new branch from master and push.

```
git clone git@github.com:cta-observatory/cta-lstchain
git switch -c hillas_uncertainties origin/master
# make changes and commit
git push -u origin hillas_uncertainties.
```

**Comment by andres-baquero** [comment]
> The diff looks much larger and you have conflicts. Please make sure you start your new branch from the current master branch. Also note, that due to the use of private test data, the CI system will not work for PRs from a fork.
> 
> I will add you yo the lst-dev team, then you need to do a fresh clone of this repository (not your fork!), create the new branch from master and push.
> 
> ```
> git clone git@github.com:cta-observatory/cta-lstchain
> git switch -c hillas_uncertainties origin/master
> # make changes and commit
> git push -u origin hillas_uncertainties.
> ```

Ok, so I have to create a new PR or just to update this one ?

**Comment by maxnoe** [comment]
@andres-baquero No, you have to create a new one from a branch in this repository (github does not allow changing the source branch of a PR).

**Comment by andres-baquero** [comment]
> > The diff looks much larger and you have conflicts. Please make sure you start your new branch from the current master branch. Also note, that due to the use of private test data, the CI system will not work for PRs from a fork.
> > I will add you yo the lst-dev team, then you need to do a fresh clone of this repository (not your fork!), create the new branch from master and push.
> > ```
> > git clone git@github.com:cta-observatory/cta-lstchain
> > git switch -c hillas_uncertainties origin/master
> > # make changes and commit
> > git push -u origin hillas_uncertainties.
> > ```
> 
> Ok, so I have to create a new PR or just to update this one ?

I ca

> @andres-baquero No, you have to create a new one from a branch in this repository (github does not allow changing the source branch of a PR).

Ok, but I can't clone I'm getting this:

$ git clone git@github.com:cta-observatory/cta-lstchain
Cloning into 'cta-lstchain'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please let me know when you add me to the lst-dev team.

**Comment by maxnoe** [comment]
@andres-baquero sorry, that just means that you don't have ssh setup. Replace the url with the https version (or add an ssh public key):
```
git clone https://github.com/cta-observatory/cta-lstchain
```

**Comment by andres-baquero** [comment]
> @andres-baquero sorry, that just means that you don't have ssh setup. Replace the url with the https version (or add an ssh public key):
> 
> ```
> git clone https://github.com/cta-observatory/cta-lstchain
> ```

I have 

> @andres-baquero sorry, that just means that you don't have ssh setup. Replace the url with the https version (or add an ssh public key):
> 
> ```
> git clone https://github.com/cta-observatory/cta-lstchain
> ```

I have cloned form the master, create a new branch, made the changes and commit but when I tried to push I'm getting this:

git push -u origin hillas_uncertainties
Username for 'https://github.com': andres-baquero
Password for 'https://andres-baquero@github.com': 
remote: Permission to cta-observatory/cta-lstchain.git denied to andres-baquero.
fatal: unable to access 'https://github.com/cta-observatory/cta-lstchain.git/': The requested URL returned error: 403

**Comment by maxnoe** [comment]
@andres-baquero You should have received an invitation to cta-observatory, did you accept that?

**Pull request closed without merging**
