### PR TITLE
Bump ctapipe_io_lst version

### LINKED ISSUE #736: Outdated version of ctapipe_io_lst
The version of `ctapipe_io_lst` required by lstchain is `~=0.9.2` (see `setup.py` and `environment.yml` files). Latest `ctapipe_io_lst` version is `0.10.0` since last May. Does this need to be updated?

### PR DESCRIPTION
**Pull request by morcuended**
Closes #736

### CODE REVIEW

**Comment by rlopezcoto** [comment]
is the empty `lstchain/scripts/tests/__init__.py` file needed?

**Comment by maxnoe** [comment]
Yes, it is needed so the tests directory is treated as a python module, which enables relative imports and running the tests in the installed package

**Review by rlopezcoto — APPROVED** [review]

**Comment by rlopezcoto** [comment]
should we re-bump here?

**Comment by maxnoe** [comment]
Let's merge as is and I make a  new PR updating ctapipe and ctapipe_io_lst

**Review by maxnoe — APPROVED** [review]

**Pull request merged**
