### PR TITLE
Use telescope ID together with telescope name during R0 to DL1 conversion

### PR DESCRIPTION
**Pull request by mexanick**
Possible fix of telescopes with the same name not being properly distinguished

Details: [Issue 633](https://github.com/cta-observatory/cta-lstchain/issues/633)

### CODE REVIEW

**Comment by mexanick** [comment]
The PR is rebased and ready for review

**Comment by mexanick** [comment]
The CI is failing for the reasons that seems to be independent of the proposed changes:
```
Run ./download_test_data.sh
./download_test_data.sh
shell: /bin/bash -e {0}
env:
    NUMBA_NUM_THREADS: 1
    MPLBACKEND: Agg
    PYTEST_ADDOPTS: --color=yes
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.10/x64/lib
    TEST_DATA_USER: 
    TEST_DATA_PASSWORD: 
Username: 
Error: Process completed with exit code 1.
```

**Comment by morcuended** [comment]
> Since the addition of the private data, the CI tests for Pull Requests from forks are not working, therefore we would like to ask to push your modified branches directly to the main cta-lstchain repo.

**Comment by mexanick** [comment]
I don't have write permissions for this

**Comment by rlopezcoto** [comment]
> I don't have write permissions for this

@mexanick just gave you write permissions

**Comment by mexanick** [comment]
Replaced by #646

**Pull request closed without merging**
