### PR TITLE
Nan timestamp

### PR DESCRIPTION
**Pull request by MaxNoe**
As discussed in #386, adding support for nan values in `unix_tai_to_utc`

I also renamed the function `unix_tai_to_time` as it does not actually convert to utc.
It correctly creates an `astropy.Time` object, that is still in tai but converts to unix utc timestamp when accessing `.unix`.

For convenience and clarity, I would suggest to compare times to `INVALID_TIME` as now defined in the module.

### CODE REVIEW

**Comment by MaxNoe** [comment]
@morcuended it deals with nan like it would be zero.

**Comment by morcuended** [comment]
> @morcuended it deals with nan like it would be zero.
> 
> So your choice now, what you want `timestamp` to be if it is missing, the conversion functin now supports both

not strong preference, I would leave it as it is now with `nan` provided it works

**Comment by rlopezcoto** [comment]
what about the interpolation, is it dealing with it properly?

**Comment by MaxNoe** [comment]
Can you point me to the interpolation code?

**Comment by morcuended** [comment]
> Can you point me to the interpolation code?

functions `linear_imputer` and `impute_pointing` in `lstchain/reco/utils.py` which interpolate missing alt/az coordinates directly. Thus missing time values should not be a problem.

**Comment by morcuended** [comment]
May you update the branch with the last merge fixing the muon output filename so I can test it?

**Comment by MaxNoe** [comment]
> Thus missing time values should not be a problem.

These are not missing anymore but `1970-01-01`, so maybe you need to explicitly filter with` time != INVALID_TIME`

**Comment by rlopezcoto** [comment]
@morcuended did you test this? can we move ahead with the merge?

**Comment by morcuended** [comment]
> @morcuended did you test this? can we move ahead with the merge?

Yes, I tested that the script runs well without problems and files are produced normally. However, I did not have the time to look into the time values themselves.

**Pull request merged**
