### PR TITLE
Update dependencies, including ctapipe to 0.11.0

### PR DESCRIPTION
**Pull request by maxnoe**
* ctapipe -> 0.11.0
* ctapipe_io_lst -> 0.11.1
* pyirf -> 0.5

Only some tests needed minor adjustments.

### CODE REVIEW

**Review by moralejo — COMMENTED** [review]
Looks good to me, but I thought you had told me that ctapipe v11 contained "breaking changes" w.r.t. v10. I am surprised of the few changes needed (at least to make tests pass).

**Review by rlopezcoto — APPROVED** [review]

**Review by morcuended — APPROVED** [review]

**Comment by maxnoe** [comment]
@moralejo here is the changelog of ctapipe 0.11, most breaking changes do not affect lstchain directly (at least not the code):

https://github.com/cta-observatory/ctapipe/releases/tag/v0.11.0

> Change default of CameraCalibrator.apply_waveform_timeshift to False (#1692) @maxnoe

lstchain set this to false explicitly, so no changes

> Consistent use of allowed_tels (#1697) @LukasNickel

This was a change that affected the unit tests and will affect the mc files >= DL1. When `allowed_tels={1, 2, 3, 4}` is used, only those telescopes will be saved in the `SubarrayDescription`, I assume that this is not a problem.   

> Raise error in CameraReadout.from_name if no corresponding file can be found (#1703) @maxnoe

Not used in lstchain (the event source provides the correct `CameraReadout`.)  

>  Remove unused io modules, fixes #1527 (#1693) @maxnoe

Not used by lstchain
  
>  Change definition of concentration_cog, fixes #1571 (#1572) @maxnoe

This will affect the DL1 concentration_cog parameter, it will have different values (but hopefully more meaningful ones)  

>   Transform warning into error for wrong config (#1658) @maxnoe

This actually found a bug, so yay!   

> Remove charge resolution tools, fixes #1634 (#1646) @maxnoe

Not used by lstchain

**Comment by moralejo** [comment]
Awesome, @maxnoe,  thanks a lot for this!

**Comment by rlopezcoto** [comment]
there are tests that are still on hold... any idea why?

**Comment by maxnoe** [comment]
@rlopezcoto Yes, these are tests that are not run anymore (since we upgraded to 0.11) but are required in the branch protection settings. 

If we agree to merge this now I will remove the old tests from the requirements and add the current ones.

Should I go ahead?

**Comment by maxnoe** [comment]
Ok, done. This needs to be merged now, all other PRs are now blocked since they only run the 0.10.5 tests until this is merged and the other PRs are updated from master.

**Comment by rlopezcoto** [comment]
yes, please, let's move forward with this, thanks

**Pull request merged**
