### PR TITLE
Mlp

### PR DESCRIPTION
**Pull request by Diestbarr**

### CODE REVIEW

**Comment by MaxNoe** [comment]
Why are trained models saved in this repository?

**Comment by Diestbarr** [comment]
Good afternoon, Maximilian,

I was trying to update my fork to match lstchain's 0.5.2 version and I
pulled a merge request by mistake.

I apologise for the inconvenience,

Diego Esteban Barranco

**Comment by vuillaut** [comment]
Hi @Diestbarr 

Thank you for the proposal and PR.
While the contribution is very much appreciated, before considering supporting many kinds of classifiers and aggressors, I'd very much like to see some benefits when adding new ones to the official pipeline.
Do you plan to present a comparison to RFs?

**Comment by MaxNoe** [comment]
Also, see for example the approach in the aict-tools that just allows any scikit learn model zo be used from the config file

**Comment by rlopezcoto** [comment]
Thanks @Diestbarr for contributing to lstchain. Even though the PR was opened by mistake as you already explained, you could transform it into a draft PR to get suggestions as that of having a look to the `aict-tools` implementation.
@Diestbarr is working with @nietootein and they were planning to do something in the line of what @vuillaut was suggesting and they will eventually show their results to the LST group, but early feedback that helps in their developments is welcome.

**Comment by Diestbarr** [comment]
Good evening, Thomas,

Throughout my final degree thesis I've done some comparisons between Random
Forest algorithms and Multi-layer Perceptron algorithms, although this is
still a work in progress. In fact, the merge pull request I've submitted
hours ago was done by mistake, when I was trying to update my fork to
lstchain's 0.5.2 version.

Thank you for your time and I apologise for the inconvenience,

Diego Esteban Barranco

**Comment by vuillaut** [comment]
It seems the original PR was a mistake, I therefore close it.
If needs be, you can reopen.

**Pull request closed without merging**
