### PR TITLE
Replace test file

### PR DESCRIPTION
**Pull request by maxnoe**
New file is not yet on the data server, but will be there tomorrow

### CODE REVIEW

**Comment by morcuended** [comment]
@maxnoe is the new test file already in the data server?

**Comment by maxnoe** [comment]
No, not yet. @kosack had some issues connecting to the server, but I think they are solved now.

But he's on vacation until the 4th

**Comment by morcuended** [comment]
@maxnoe, @kosack, a friendly reminder for the replacement of the test file.

**Comment by maxnoe** [comment]
Test file is now there, let's see

**Comment by morcuended** [comment]
Maybe add a test for r0 to dl1 script running without input argument to make sure it works in the future.

**Comment by morcuended** [comment]
Added a test to check that running the script without input argument also works. I think this is good to go.

**Review by morcuended — APPROVED** [review]

**Pull request merged**
