### PR TITLE
add 4 scripts of prototype for applying DRS4 sampling interval correction

### PR DESCRIPTION
**Pull request by yutonogami**
* The create_sampling_interval.py can create the counts table of coming test-pulses for all pixels to create sampling intervals table. It should use when some LST-camera modules are changed.
* The ConvertCountsToInterval.py can merge sevelar counts tables made by create_sampling_interval.py and convert the counts to sampling intervals. It should use when some LST-camera modules are changed.
* The charge_calculation.py is example script to apply sampling intervals (using ROOT). It will be merged only the algorithm of applying sampling intervals to LSTR0Correction class. The sampling interval correction should use to calibrate raw waveform.
* The merge_hist.py can merge the result files to a root-file using ROOT. It will be delete when the algorithm of applying sampling interval correction is added to LSTR0Correction class.

### CODE REVIEW

**Comment by yutonogami** [comment]
I will modify these codes. Sorry...
(If I finish modifying them, I will reopen as soon as possible.)

**Comment by rlopezcoto** [comment]
@FrancaCassol, @pawel21 could you please have a look to this PR? Thanks!

**Comment by pawel21** [comment]
Hi, I wonder about ROOT dependecies . @rlopezcoto Can we use ROOT in cta-lstchain?

**Comment by vuillaut** [comment]
> Hi, I wonder about ROOT dependecies . @rlopezcoto Can we use ROOT in cta-lstchain?

I would strongly advise against. Why do you need ROOT ?

**Comment by pawel21** [comment]
> > Hi, I wonder about ROOT dependecies . @rlopezcoto Can we use ROOT in cta-lstchain?
> 
> I would strongly advise against. Why do you need ROOT ?

I don't need, but I see ROOT in 'charge_calcuration.py' and another files.

**Comment by rlopezcoto** [comment]
Hi @pawel21, @yutonogami, we cannot use ROOT in lstchain. 
If some ROOT files are needed to be read(?), uproot can be used, but I do not think that is the case.

**Comment by vuillaut** [comment]
> > > Hi, I wonder about ROOT dependecies . @rlopezcoto Can we use ROOT in cta-lstchain?
> > 
> > 
> > I would strongly advise against. Why do you need ROOT ?
> 
> I don't need, but I see ROOT in 'charge_calcuration.py' and another files.

Ha yes did not look at the PR. Indeed ROOT should not be used.
I join @rlopezcoto,  we could use `uproot` if (only) necessary.

**Comment by FrancaCassol** [comment]
Dear @yutonogami,

actually we need in lstchain/calib/camera just the script that permits to calculate the time sampling correction and the function in  LSTR0Corrections that permits to apply them.
I suggest the following changes: 
- please merge  sampling_interval_count_pulse_per_cell.py and sampling_interval_counts_to_interval.py in a single script, looping directly on the different input files and avoiding to go through an intermediate output step for the fits files (or do you have a deep reason for this intermediate step?)
- Remove for this PR all the code related to ROOT (that means the reaming modules) and move all the plotting examples that you want to provide inside a single notebook in the directory cta-lstchain/notebooks  (without using Root!). Please do it in a second PR. So that we don't block this one

What is missing then is a fast function in LSTR0Corrections for applying the calibration in LST1. @pawel21 could you please provide this function taking inspiration from the code in sampling_interval_charge_dist.py ?

@yutonogami when the function will be there you can use it inside the notebook.

**Comment by yutonogami** [comment]
Dear @Franca and all,

Thanks for your suggestions!

> please merge sampling_interval_count_pulse_per_cell.py and sampling_interval_counts_to_interval.py in a single script, looping directly on the different input files and avoiding to go through an intermediate output step for the fits files (or do you have a deep reason for this intermediate step?)

The sampling intervals (coefficients) calculation needs 10^6 events per a pixel at once. But "event_source" can only read LST1.[1-4].RunXXXX.xxxx.fits,fz (i.e. 4 files ), it is not equivalent to 10^6 events... So I didn't merge these scripts.

> Remove for this PR all the code related to ROOT (that means the reaming modules) and move all the plotting examples that you want to provide inside a single notebook in the directory cta-lstchain/notebooks (without using Root!). Please do it in a second PR. So that we don't block this one

I will modify all scripts related to ROOT to  renewed scripts not related.

**Comment by FrancaCassol** [comment]
Dear @yutonogami,
> 
> The sampling intervals (coefficients) calculation needs 10^6 events per a pixel at once. But "event_source" can only read LST1.[1-4].RunXXXX.xxxx.fits,fz (i.e. 4 files ), it is not equivalent to 10^6 events... So I didn't merge these scripts.

Just loop on all the files inside a single script, declaring at each iteration a new event_source. Is there a problem with that?

> I will modify all scripts related to ROOT to renewed scripts not related.
As said, the visualisation scripts should not be in this directory. Here we want only the calibration code. The best is that you put them in a single notebook. Otherwise, please compact them in a single script and move it in the script directory, with a clear description about its purpose

**Comment by kosack** [comment]
> Just loop on all the files inside a single script, declaring at each iteration a new event_source. Is there a problem with that?

Just to note, you can use an EventSource as a context manager, so that the files get closed at the end (and memory doesn't explode). E.g.:
```py3
for filename in list_of_files:
    with event_source(filename) as source:
        for event in source:
            ...
```

**Comment by FrancaCassol** [comment]
Wonderful! Thanks for the hint @kosack

**Comment by yutonogami** [comment]
Dear @FrancaCassol and @kosack,

> > please merge sampling_interval_count_pulse_per_cell.py and sampling_interval_counts_to_interval.py in a single script, looping directly on the different input files and avoiding to go through an intermediate output step for the fits files (or do you have a deep reason for this intermediate step?)
> 
> The sampling intervals (coefficients) calculation needs 10^6 events per a pixel at once. But "event_source" can only read LST1.[1-4].RunXXXX.xxxx.fits,fz (i.e. 4 files ), it is not equivalent to 10^6 events... So I didn't merge these scripts.

I forgot to tell you about the execution speed of sampling_interval_count_pulse_per_cell.py and sampling_interval_count_pulse_per_cell.py. 
The total execution speed of these scripts is about 30 minutes when I executed the scripts using 10^6 events (assuming that sampling_interval_count_pulse_per_cell.py is executed as multiple jobs using "slurm" on IT-container server).
The other hand, I merged the 2 scripts introducing @kosack's hint (thanks, @kosack) and also verified it using 10^6 events. The execution speed of the merged script is about 7 hours 30 minutes...

Which is the more important, usability or execution speed? 
(I'm modifying other scripts.)

**Comment by yutonogami** [comment]
Dear @FrancaCassol, @pawel21, all,

I and Hide think we should  just store the calibration constants in a calibration file separately from data files and this calibration can be included in the R1 -> DL0 processing. 
The reason is showed the attached file:
[20200130_timing_calib_strategy.pdf](https://github.com/cta-observatory/cta-lstchain/files/4133102/20200130_timing_calib_strategy.pdf)

**Comment by FrancaCassol** [comment]
Dear @yuto, 
I think there was not doubt that the calibration constant must be written in a separate calibration file.
Could you please push your last version of the code so to permit a detailed review?

**Comment by rlopezcoto** [comment]
@yutonogami is there any progress on this?

**Comment by moralejo** [comment]
Hi @yutonogami,

we really need to move this forward. Please let us know if and in which timescale you can proceed with finalizing the implementation. If you need additional help, or prefer someone else to take over, let us know as well. Thanks!

**Comment by yutonogami** [comment]
Dear @FrancaCassol, @rlopezcoto, @moralejo,

Sorry for my too late reply...
(I have been joining the camera module QC of the LST2-4 from Feb. 1st to Mar. 13th at IAC-Tec.)
The sampling-coefficient-creation script almost ready, so I'll upload the the script by tomorrow.

Best regards,
Yuto

**Comment by rlopezcoto** [comment]
> I'll upload the the script by tomorrow

@yutonogami any update on this?

**Comment by rlopezcoto** [comment]
Hi @yutonogami, I'm sorry, but this implementation should be added soon, otherwise we will have to open a different PR to  include it

**Comment by yutonogami** [comment]
Dear @rlopezcoto,

Sorry for very late update...
I modified the scripts about sampling interval creation. On the other hand, I'm being made the notebook about example of charge calculation.

**Comment by yutonogami** [comment]
Dear all,

I forgot to tell about the interval file creation.
The interval file created from these scripts is not good to use to the calibration. There seems to be something wrong with R0->R1 conversion... (I am investigating now)
That's why the interval file created from current R1 data is incorrect.
I will let you know if I have any progresses about this problem.

**Comment by vuillaut** [comment]
This should go into `ctapipe_io_lst`? Is it already? Shall this be closed or relived?

**Comment by FrancaCassol** [comment]
Hi @vuillaut,

this PR concerns the code to create the sampling interval coefficients file, so it is supposed to remain in lstchain. Dear @yutonogami, did you finalise your procedure for extracting the coefficients?

The code for applying the coefficients is in PR [https://github.com/cta-observatory/cta-lstchain/pull/552](https://github.com/cta-observatory/cta-lstchain/pull/552) and indeed it is worth to move it to ctapipe_io_lst as soon as the ctapipe_compatible branch is approved. Notice however that these corrections will be most probably not applied to all the events but only to the flat-field events in order to reduce the systematic errors of the calibration values (which are now corrected with the global scaling).

**Comment by rlopezcoto** [comment]
This is dead since a long time... the code for applying the coefficients is now on `ctapipe_io_lst`

**Pull request closed without merging**
