### PR TITLE
WIP: Getting mc info using `pyeventio` to compute IRF

### PR DESCRIPTION
**Pull request by vuillaut**
Hi @misabelber @rlopezcoto 

I am opening this PR to work together on building functions to get mc info and later compute IRF.
You may contribute by pulling and pushing on the PR.
Depending how you called your remote, you may use:
```
git fetch upstream pull/71/head:mc_info
git checkout mc_info
```
Update code and push again:
```
git push upstream pull/71/head
```

Adding a function to recompute the energy distribution from mc info and a notebook as an example.

### CODE REVIEW

**Comment by misabelber** [comment]
Nice @vuillaut ! I tried the notebook and works perfectly. I'll start working on this PR on computing the sensitivity for real data.
Also, I'll explore how to get the events data using eventio instead of ctapipe.io.event_source. 
Thank you!

**Comment by misabelber** [comment]
Hi @vuillaut  ! I've created a modification of @rlopezcoto  notebook to calculate the sensitivity, but using true simulated data and pyeventio, but I don't know how to push it to this PR, if it's possible (I tried "git push upstream pull/71/head" but doesn't seem to work)

**Comment by vuillaut** [comment]
Hey @misabelber 
I think that actually, only maintainers can push changes to PR...
With script code, you could insert the changes as a review but that's not really practical with notebooks.
So here maybe doing a new PR is the best... If you did
```
git fetch upstream pull/71/head:mc_info
```
then the history from @rlopezcoto will be kept. So no autorship issues ;-)

**Comment by misabelber** [comment]
Ok then! Thanks :)

**Pull request merged**
