### PR TITLE
Fix a failing test on DL3 Tool

### PR DESCRIPTION
**Pull request by chaimain**
A test on DL3 Tools when using IRF interpolation methods was failing as it required a list of IRFs which are not present as fixtures for the scope of the test session. These IRFs are created and tested in `lstchain/high_level/tests/test_interpolate` (through some "lengthy" code) for almost all combinations of IRF interpolations. 
As such, it is not essential to have separate and similar tests on DL3 Tools, for testing the same functionality.

This was missed in the earlier PR #711 as I tested in sequential order instead of in parallel (as done in CI).

In case, we require to have the DL3 Tools tested for the full functionality again, we would just need to shift ~150 lines of code from `lstchain/high_level/tests/test_interpolate.py` to `lstchain/conftest.py`

### CODE REVIEW

**Comment by moralejo** [comment]
Hi, 
probably unrelated, but I realized that the tests in high_level do not pass in my Mac (while they work on linux). 
This is the same for the master and for the interp_irfs branch

```
lstchain/data/tests/test_normalised_pulse_template.py::test_load_from_file_and_miscellaneous PASSED [  4%]
lstchain/high_level/tests/test_hdus.py::test_create_event_list ERROR     [  5%]
lstchain/high_level/tests/test_hdus.py::test_create_obs_hdu_index ERROR  [  5%]
lstchain/high_level/tests/test_hdus.py::test_get_timing_params PASSED    [  6%]
lstchain/high_level/tests/test_interpolate.py::test_load_irf_grid PASSED [  6%]
lstchain/high_level/tests/test_interpolate.py::test_interp_irf FAILED    [  7%]
lstchain/high_level/tests/test_interpolate.py::test_compare_irfs PASSED  [  7%]
```

When looking in more detail, I don't understand anything, the error seems to be in the r0 to dl1 step

```
==================================== ERRORS ====================================
___________________ ERROR at setup of test_create_event_list ___________________

temp_dir_observed_files = PosixPath('/private/var/folders/cn/jhp87yg56455zyhkzz36mhl40000gn/T/pytest-of-moralejo/pytest-18/observed_files0')
run_summary_path = PosixPath('/private/var/folders/cn/jhp87yg56455zyhkzz36mhl40000gn/T/pytest-of-moralejo/pytest-18/observed_files0/RunSummary_20200218.ecsv')

    @pytest.mark.private_data
    @pytest.fixture(scope="session")
    def observed_dl1_files(temp_dir_observed_files, run_summary_path):
...
...
E             File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/si
te-packages/astropy/io/ascii/core.py", line 743, in check_column_names
E               raise InconsistentTableError(
E           astropy.io.ascii.core.InconsistentTableError: Length of names argume
nt (10) does not match number of table columns (3)
```
Anyone has an idea of what may be going on?

**Review by gabemery — APPROVED** [review]
Ok with removing the test if it leads to failure. (also for some reason it doesn't reduce coverage?)

**Comment by gabemery** [comment]
@moralejo Is this the full error message you get? It doesn't include the line where you get the error.

**Comment by chaimain** [comment]
> Ok with removing the test if it leads to failure. (also for some reason it doesn't reduce coverage?)

It does reduce the coverage, but of the DL3 Tool file, https://app.codecov.io/gh/cta-observatory/cta-lstchain/pull/1092/blob/lstchain/tools/lstchain_create_dl3_file.py which is an indirect change with respect to this PR.

**Review by rlopezcoto — CHANGES_REQUESTED** [review]
before removing the test because it is not passing, let's try to figure out what is the problem.

**Comment by moralejo** [comment]
> @moralejo Is this the full error message you get? It doesn't include the line where you get the error.

The error itself seems to happen when running  lstchain_data_r0_to_dl1, and more specifically, in ctapipe_io_lst, when it tries to read in the drive report of the test data
https://github.com/cta-observatory/ctapipe_io_lst/blob/28b4a1b55e58fbacae6fe52c90b0e6e28433b984/ctapipe_io_lst/pointing.py#L96-L121

```
test_data/real/monitoring/DrivePositioning/drive_log_20200218.txt

astropy.io.ascii.core.InconsistentTableError: 
ERROR: Unable to guess table format with the guesses listed below:
[...]
```
And indeed, the format does not seem to be what it tries to read. I can reproduce it outside of the tests (both running the lstchain_data_r0_to_dl1 script and directly reading in the file)

`astropy.io.ascii.core.InconsistentTableError: Length of names argument (10) does not match number of table columns (20)
`

**Comment by gabemery** [comment]
@moralejo It seems like a dedicated issue will be needed to discuss this.

**Comment by moralejo** [comment]
> @moralejo It seems like a dedicated issue will be needed to discuss this.

Let's discuss here: #1094

**Comment by rlopezcoto** [comment]
Now that we have worked out the problems with the tests in #1094 and that it was unrelated to this PR, @moralejo can you confirm that tests pass on this branch and that everything is alright for it to be merged?

**Review by rlopezcoto — APPROVED** [review]

**Pull request merged**
