### PR TITLE
Add sphinx.ext.githubpages to docs config

### PR DESCRIPTION
**Pull request by rlopezcoto**
For proper docs deployment, add a .nojekyll file

### CODE REVIEW

**Comment by maxnoe** [comment]
Shouldn't this be in the root of the resulting build? Does putting it into the `docs/` foder achieve this?

**Comment by rlopezcoto** [comment]
> Shouldn't this be in the root of the resulting build? Does putting it into the `docs/` foder achieve this?

I thought it was enough to include it here, it was working when I did the original PR in my fork, but maybe something else was changed?

**Comment by maxnoe** [comment]
Is the `.nojekyll` inside `docs/build/_html` when you build locally?

**Comment by rlopezcoto** [comment]
no, it is not there, but I already pushed a `.nojekyll` file to the `gh-pages` branch... will it be removed the next time the docs are deployed?

**Comment by maxnoe** [comment]
Yes, `gh-pages` is an orphan branch with only one commit that is overwritten each time the docs are deployed.

**Comment by maxnoe** [comment]
ctapipe has no `.nojekyll` and the deploy works, so what is the problem here?

This looks ok, doesn't it?

https://cta-observatory.github.io/cta-lstchain/

**Comment by morcuended** [comment]
I think `.nojekyll` is not needed. The webpage is working already.

**Comment by rlopezcoto** [comment]
No, it was working because I added the `.nojekyll` file by hand to the `gh-pages` branch:
https://github.com/cta-observatory/cta-lstchain/tree/gh-pages

I just removed it and rebuilt it, you can check now, it does not look nice:

Screenshot 2021-11-16 at 16 24 47
 
`ctapipe` (and apparently also `pyirf`) have `.nojekyll`:
https://github.com/cta-observatory/pyirf/blob/gh-pages/.nojekyll
https://github.com/cta-observatory/ctapipe/blob/gh-pages/.nojekyll

in the `gh-pages`, but I'm figuring out how it got there.

**Comment by maxnoe** [comment]
It has to be the `"sphinx.ext.githubpages"` extension

**Comment by rlopezcoto** [comment]
> It has to be the `"sphinx.ext.githubpages"` extension:

Right, thanks!

**Review by morcuended — APPROVED** [review]

**Pull request merged**
