### PR TITLE
removing intercept from configs

### PR DESCRIPTION
**Pull request by vuillaut**

### CODE REVIEW

**Comment by morcuended** [comment]
Looking at the `lstchain_standard_config_keep_all_events.json` file I realize that it's no longer up to date. It needs to be either updated or entirely removed.

**Comment by vuillaut** [comment]
> Looking at the `lstchain_standard_config_keep_all_events.json` file I realize that it's no longer up to date. It needs to be either updated or entirely removed.

Ok, thanks for the check.
Is it used at all? (if not I'd remove it to keep things cleaner)

**Comment by morcuended** [comment]
> Ok, thanks for the check.
> Is it used at all? (if not I'd remove it to keep things cleaner)

I would say that not anymore

**Comment by rlopezcoto** [comment]
the config to keep all events, is it really unused @morcuended?

**Comment by morcuended** [comment]
> the config to keep all events, is it really unused @morcuended?

I'm not using it at least. Just the standard config file or a modified one if a different cleaning setting is required. But not exactly this one that became outdated quite some time ago.

**Comment by rlopezcoto** [comment]
ok, so I agree to remove it to avoid confusion, thanks @vuillaut

**Pull request merged**
