### PR TITLE
Refactor onsite scripts

### PR DESCRIPTION
**Pull request by maxnoe**
* Use `Path` in `create_pro_symlink`, add test
* Factor out functions to find R0 subruns, pedestal files, time calibration files, run summaries and add tests

### CODE REVIEW

**Comment by FrancaCassol** [comment]
Hi, I suggest to postone this to after the release production

**Comment by maxnoe** [comment]
> Hi, I suggest to postone this to after the release production

But it fixes at least two issues we found trying to run the current version. The link creation (which I also fixed in a single change here #913) and the `Trash` situation

**Comment by maxnoe** [comment]
I tested that I can produce all calibration files with the exception of the filter scan / systematics file for the test data and the crab sample night 2021-11-20.

If you could test running it on a calibration filter scan, we could solve these issues now.

**Comment by FrancaCassol** [comment]
Already that we are refactoring, in recent DPPS meeting and documentation I saw that concerning the data, it is used the term "Cat-A" instead of "LevelA". Should we better change it now?

**Comment by maxnoe** [comment]
That is a real change! Here I just improve the code quality by refactoring out functions and fixing some issues.

I would make the change you propose in a different PR.

**Comment by FrancaCassol** [comment]
Ok, let me check the filter scan

**Comment by moralejo** [comment]
> Already that we are refactoring, in recent DPPS meeting and documentation I saw that concerning the data, it is used the term "Cat-A" instead of "LevelA". Should we better change it now?

I agree with changing that before the 0.9.2 release

**Review by FrancaCassol — APPROVED** [review]

**Pull request merged**
