### PR TITLE
request ctaplot 0.6.4 to fix the seaborn style issue

### LINKED ISSUE #1161: docs build fialing due to seaborn style in mc sensitivity
```
 Failed to import lstchain.scripts.lstchain_mc_sensitivity.
Possible hints:
* OSError: 'seaborn-deep' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
* AttributeError: module 'lstchain.scripts' has no attribute 'lstchain_mc_sensitivity'
```

### PR DESCRIPTION
**Pull request by vuillaut**
fixes #1161 
closes #1166

### CODE REVIEW

**Comment by rlopezcoto** [comment]
tests are not passing, do you have to upload ctaplot manually?

**Comment by morcuended** [comment]
is ctaplot already in conda forge?

**Comment by maxnoe** [comment]
@vuillaut needs to merge the pull request here:
https://github.com/conda-forge/ctaplot-feedstock/pulls

**Comment by morcuended** [comment]
Do we also then want to allow using mpl 3.8?

**Review by morcuended — APPROVED** [review]

**Pull request merged**
