### PR TITLE
Solve matplotlib style problem that was making labels non-legible

### PR DESCRIPTION
**Pull request by rlopezcoto**
Solution to work out the problem with the matplotlib style/backend that was described in #401. While this is worked out, these lines should force the matplotlib style to the 'default' one, that was working before for all the plotting.

### CODE REVIEW

**Comment by vuillaut** [comment]
Hi
- I just shipped ctaplot 0.5.2 fixing the styling issue - one now can actively set ctaplot style with `ctaplot.set_style()` if desired
- We can still force default style in lstchain to avoid problems in the future.

**Comment by MaxNoe** [comment]
Both these solution are not ideal.

matplotlib supports context manager for setting styles. Do not set them globally! And don't override user defined styles by setting it back to defaults.

This breaks any matplotlib mechanism to set styles outside of code (environment variables, local matplotlibrc, global matplotlibrc).

**Comment by vuillaut** [comment]
> This breaks any mechanism to set matplotlib options outside of code.
> 
> Don't mess with these things, please just fix the underlying issue.

Well, as said, if the problem was indeed ctaplot, I think it is fixed.

**Comment by rlopezcoto** [comment]
Agreed that this may not be ideal, but at least we need a temporary solution for all the datacheck/calibration plots to be displayed. 
We can discuss a better, more general solution to remove those lines in the future, but we really need to move on with the release right now, and without this fix, the next set of reprocessed data will have very bad style, not legible plots...

**Comment by rlopezcoto** [comment]
ok, I tested `ctaplot=0.5.2` and the style is again ok, so I removed the forcing of the matplotlib "default" style. 
Still, we may want to think on a way of avoiding these problems in the future...

**Comment by vuillaut** [comment]
> ok, I tested `ctaplot=0.5.2` and the style is again ok, so I removed the forcing of the matplotlib "default" style.
> Still, we may want to think on a way of avoiding these problems in the future...

Glad this is fixed and sorry for the mess.

**Pull request merged**
