### PR TITLE
Add correction of the systematic term to the F-factor method

### PR DESCRIPTION
**Pull request by FrancaCassol**
This PR adds:
- the possibility to correct the the F-factor method for the quadratic component if the correction file is given (by default not given for the moment)
- a trailet to the calibration script to allow the selection of a configuration file different than the default one (for tests)
- two new plots in the calibration check pdf 

I am still performing some test so this is a draft PR

### CODE REVIEW

**Comment by FrancaCassol** [comment]
Hi, 
the test shows that correcting the F-factor method for the B term we obtain a gain estimation which depends much less from the signal charge (some small systematic differences remain to be further studied):

Scan of February, before B corrections (estimated gains increases with charge):
plot_gain_vs_pe_20210218_no_corrected


Scan of February, after B corrections estimated with the scan of April (most gains are within 2% close to the gain estimated with filter 52):

plot_gain_vs_charge_20210218_B_corrected

**Comment by FrancaCassol** [comment]
Hi, 
would be it possible to review this PR? 
Thanks

**Review by pawel21 — APPROVED** [review]

**Review by maxnoe — COMMENTED** [review]
This code looks fine, however it does not explain where this `systematic_correction` file comes from or how one can create it.

Where is the code to construct this file? Could this be added to the help / docstrings?

**Comment by maxnoe** [comment]
@FrancaCassol ok. But that also means, that there now test for this right?

Wouldn't the natural order be to first make a PR for the creation of the file and then one that depends on its existence?

If the structure is already final, I can also add the file to the test data so you can add a unit test for it.

**Comment by FrancaCassol** [comment]
Ok, then I do a PR with all together

**Pull request closed without merging**
