### PR TITLE
fixing charge integration with new API from ctapipe

### PR DESCRIPTION
**Pull request by vuillaut**
Trying to fix the charge integration.
Probably need review and help from @FrancaCassol

### CODE REVIEW

**Comment by rlopezcoto** [comment]
Thanks, this is breaking all the Travis tests...
If you can do this soon, I'd wait before going for further PR reviews.
There seems to be still a couple of errors in `reco/dl0_to_dl1.py` and `reco/dl1_to_dl2.py`, maybe @misabelber can also give you a hand.

**Comment by vuillaut** [comment]
Hi.

Tests should be passing now.
However, I'd still like @FrancaCassol to have a quick look at the calibration code that I modified.

**Comment by rlopezcoto** [comment]
I'll wait for @FrancaCassol to have a quick look

**Comment by rlopezcoto** [comment]
Hi, this needs to be merged for tests to pass. I'm approving it now, if @FrancaCassol does have time today to have a look, please do, otherwise I'll merge it

**Comment by rlopezcoto** [comment]
I merged it to carry on with the other PRs, please @FrancaCassol have a look whenever you have time to check that the code is doing what it is supposed to. Thanks

**Comment by FrancaCassol** [comment]
Hi @rlopezcoto,
sorry for this late reply (I took some days off), I am going soon to have a look at this code

**Pull request merged**
