### PR TITLE
DL1 scaling

### LINKED ISSUE #433: scaling MC intensity
Discussed during LST analysis call, June 15th.

We need to scale the MC to match the real data (seems to be easier than the other way around).
Is it necessary to do it at R1/DL0 level or can it be done at DL1 level (on the charge images, before cleaning and parameters extraction)?
The former will be much more complicated.

Note: it might get even more complicated when going for ctapipe v0.8 and the DL1 writer tool which is not meant for these kinds of tweaks but we can leave that point for later.

tagging @moralejo @FrancaCassol for discussion

### PR DESCRIPTION
**Pull request by vuillaut**
resolves #433

### CODE REVIEW

**Comment by moralejo** [comment]
Thanks!
Just for clarity,  I would rename  mc_dl1_scaling_factor  to  "mc_dl1a_scaling_factor"  or "mc_light_scaling_factor"

**Comment by MaxNoe** [comment]
> Just for clarity, I would rename mc_dl1_scaling_factor to "mc_dl1a_scaling_factor" or "mc_light_scaling_factor"

It's applied only to `dl1.image`, so why not `mc_image_scaling`?

**Comment by vuillaut** [comment]
`image` seemed more appropriate, I made the change.

**Comment by vuillaut** [comment]
Note: with `ctapipe v0.8` this correction can be done with the `relative_factor`  in the DL1 Calibration Container.

**Pull request merged**
