### PR TITLE
New correction method for the DRS4 spike

### PR DESCRIPTION
**Pull request by TomohikoOka**
This modification is related to #571.
I have modified the correction method of the DRS4 spike from the interpolation method.
The new method of the correction is to subtract with a fixed value of ~50 ADC counts.
Not to include a fixed value in the lst-chain script, the value of the spike ADC counts can be given from an input table by analyzers. The calculation and making a spike table can be performed with lstchain_data_create_drs4_spike_table.py in the script directory of lst-chain.
Furthermore, the correction algorithm in r0.py can be done without the input table. 
In that case, the default value described in the r0.py will be used for the spike correction.

### CODE REVIEW

**Comment by moralejo** [comment]
How stable is the size of the spikes?  Can you provide some info on that?

Also: is the spike table created with a DRS4 pedestal calibration file? If so, wouldn't it be simpler to incorporate this in the script calculating the DRS4 corrections?

**Comment by toka2018** [comment]
How stable is the size of the spikes? Can you provide some info on that?

Also: is the spike table created with a DRS4 pedestal calibration file? If so, wouldn't it be simpler to incorporate this in the script calculating the DRS4 corrections?
https://drive.google.com/file/d/1AO2vW1AevSu49tYo209lo1DPz8f7XQmH/view?usp=sharing

**Comment by toka2018** [comment]
> How stable is the size of the spikes? Can you provide some info on that?

I summarized it. Please read my slide.
https://drive.google.com/file/d/1AO2vW1AevSu49tYo209lo1DPz8f7XQmH/view?usp=sharing


> Also: is the spike table created with a DRS4 pedestal calibration file?

Yes.

> If so, wouldn't it be simpler to incorporate this in the script calculating the DRS4 corrections?

I see. 
I separated the pedestal and spike calculation code because I avoid modifying the conventional code calculating the pedestal. 
If you think that combining the two calculation codes is better than to separate, I  will do it.

**Comment by maxnoe** [comment]
> I separated the pedestal and spike calculation code because I avoid modifying the conventional code calculating the pedestal.
If you think that combining the two calculation codes is better than to separate, I will do it.

Having the same calculations done in the same script does not mean the actual calculation must be intertwined.

The calculations can easily be separated (e.g. using two components) that are then used in the same script.

**Comment by toka2018** [comment]
> Having the same calculations done in the same script does not mean the actual calculation must be intertwined.
> The calculations can easily be separated (e.g. using two components) that are then used in the same script.

OK. I will incorporate the spike calculation algorithm in the pedestal calculation script (not separate the two codes).

**Comment by SeiyaNozaki** [comment]
btw, should we wait for the ctapipe-compatible event source in ctapipe_io_lst and directly contribute to it after the release?

**Comment by jsitarek** [comment]
About the implementation together with the DRS4 pedestal table: I think it is not as simple as substituting one entry of the table with another, because the spike position depends on current and previous first capacitor value, so simply the procedure is different (otherwise we would not have those spikes in the first place :-) ), still, things can be written in the same piece of code, but with somewhat different operations. 
Tomohiko, I do not remember from your previous studies if you tested this procedure also for randomly arriving pulses (e.g. calibration pulses intealeaved into real data)

**Comment by maxnoe** [comment]
@jsitarek We were not proposing to have it in the same data structure, just compute it in the same script and store the coefficients (in a different table) in the same file.

**Comment by TomohikoOka** [comment]
Hi,

Sorry for the very late reply.

I combined the above two code and tested with some data. 
https://drive.google.com/file/d/1SVkbHboI0apW6QRNnQioWNGT_HvDfmyR/view?usp=sharing

**Comment by moralejo** [comment]
Hi @jsitarek, can we revive this?  What do you think of this correction?
@maxnoe made me note that the %32 spikes are currently not corrected, being relatively small. Could this method be used for them as well?

**Comment by jsitarek** [comment]
Hi @moralejo @TomohikoOka 

apologies for a long delay. I reviewed the related PR on the ctapipe_io_lst. 
About this one, it has some conflicts because of refactoring the code from r0.py to ctapipe_io_lst. can you @TomohikoOka can you update the code accordingly and check that it still works with the current reading scheme, afterwards I can make a quick review of the new code

about the comment about 32-period spikes, contrary to those broad "Spike A", the period-32 spikes are not predictable, so we would have to interpolate them instead of subtracting. @SeiyaNozaki made a study that they are connected with the long time lapse times, and during regular data taking (with a few kHz rate) this happens very rarely. Adding the fact that they are also pretty small, they are not really worth to be interpolated.

**Comment by TomohikoOka** [comment]
Dear @jsitarek, 

Thank you for your reply!

My code for the "cta-lstchain" was (i) to calculate the ADC value of DRS4 spikes and (ii) to correct spike events.
@maxnoe and @SeiyaNozaki currently seem to incorporate them into "ctapipe-io-lst," respectively.
(i) https://github.com/cta-observatory/cta-lstchain/pull/725 (ii) https://github.com/cta-observatory/ctapipe_io_lst/pull/96

I will help them if they want.

**Comment by maxnoe** [comment]
The code this is targeting was removed in lstchain and added to `ctapipe_io_lst`. There is a new PR open regarding calculation of spike heights here and application in ctapipe_io_lst respectively. So I am closing this one.

**Pull request closed without merging**
