### PR TITLE
Change np.float by float, since np.float cannot be used anymore with …

### PR DESCRIPTION
**Pull request by marialainez**
…the new version of numpy

### CODE REVIEW

**Review by maxnoe — APPROVED** [review]

**Review by morcuended — APPROVED** [review]
We have to merge this and make a hotfix release to set it for production in OSA

**Comment by maxnoe** [comment]
You could also just simply down grade numpy for nownin the osa env, right?

**Comment by maxnoe** [comment]
Numpy 1.23 to be precise, those aliases were removed in 1.24

**Comment by morcuended** [comment]
I installed 1.23.5 and worked fine

**Comment by rlopezcoto** [comment]
So no release needed?

**Comment by maxnoe** [comment]
This change is here is good and should be merged and will make life easier, if this needs an immediate release is another question.

**Comment by morcuended** [comment]
No need for the release, pinning numpy version is enough

**Pull request merged**
