### PR TITLE
Add .mailmap

### PR DESCRIPTION
**Pull request by maxnoe**
In preparation for the "How to contribute to lstchain part" on friday, I saw that we have a bit of a Tohuwabohu in the log when it comes to people.

Added a .mailmap to resolve that. It took the "most official looking" version I could find for people.

With the mailmap, shortlog now looks like this:

```
$ git shortlog -sne --all
   927  Ruben Lopez Coto <ruben.lopezcoto@pd.infn.it>
   844  Thomas Vuillaume <thomas.vuillaume@lapp.in2p3.fr>
   618  Abelardo Moralejo Olaizola <moralejo@ifae.es>
   413  Franca Cassol <cassol@cppm.in2p3.fr>
   370  Maximilian Nöthe <maximilian.noethe@tu-dortmund.de>
   241  Daniel Morcuende <dmorcuen@ucm.es>
   209  Chaitanya Priyadarshi <cpriyadarshi@ifae.es>
   195  Mab Bernardos <m.isabel.bernardos@gmail.com>
   163  Jose Enrique Ruiz <jer@iaa.es>
   147  Paweł Gliwny <p.gliwny@gmail.com>
   136  Seiya Nozaki <nozaki.seiya.1211@gmail.com>
    34  Emery Gabriel <gabriel.emery@lpnhe.in2p3.fr>
    32  Cyril Alispach <cyril.alispach@gmail.com>
    32  Enrique Garcia <garcia@lapp.in2p3.fr>
    27  Luca Foffano <luca.foffano@cern.ch>
    26  Gabriel Emery <gabriel.emery@cern.ch>
    24  Mykhailo Dalchenko <mykhailo.dalchenko@cern.ch>
    15  Yves Renier <yves.renier@unige.ch>
    14  Lab Saha <labsaha@ucm.es>
    11  Mikael Jacquemont <mikael.jacquemont@lapp.in2p3.fr>
    10  Dominik Neise <neised@phys.ethz.ch>
     9  Juan <61684795+juanjq@users.noreply.github.com>
     8  Thomas Gasparetto <thomas.gasparetto@ts.infn.it>
     7  Mykhailo Dalchenko <mexanick@users.noreply.github.com>
     6  Jouvin <lea.jouvin@apc.in2p3.fr>
     6  Yukiho Kobayashi <yukihok@icrhome02.icrr.u-tokyo.ac.jp>
     5  Roberta Pillera <roberta.pillera@gmail.com>
     5  autoblack <blackaction@lstchain.com>
     4  Andres Baquero <obaquero@ucm.es>
     3  Julian Sitarek <jsitarek@uni.lodz.pl>
     2  aaguasca <arnauaguasca@gmail.com>
     2  jakub jurysek <jakub.jurysek@cp02.ctan.cta-observatory.org>
     1  Federico Di Pierro <dipierr@HP-EliteBook-840-G3>
     1  cta <cta@dragon6.cr.scphys.kyoto-u.ac.jp>
     1  juanjimenezquiles34@gmail.com <jjimenezq@mic01.magic.pic.es>
     1  mari-taka <maritaka@icrr.u-tokyo.ac.jp>
     1  sn621 <ssakurai@icrr.u-tokyo.ac.jp>
     1  yiwamura <iwamura@icrr.u-tokyo.ac.jp>
```

If you want to appear with any other email address or name spelling, just write it here or directly update the file

### CODE REVIEW

**Comment by DirkHoffmann** [comment]
The purpose of this list is not clear for me. It is very close to the limit of what [GDPR](https://gdpr.eu/) allows if not beyond.

Assuming there are good reasons to make it work optimally, here are some hints:
- Why not use an [official CTA member list](https://portal.cta-observatory.org/Bodies/ProjectOffice/Lists/People) as described [here](https://forge.in2p3.fr/issues/46660)?
- The noreply.github.com address is likely to be pointless
- as is username **cta**.
- sn261 has a real world name (which is easy to guess from his address for his CTA colleagues).
- I am quite sure Lea's address is definitely out of order at APC.
- We had a similar problem in the context of SVN authorship migration, which was solved [here](https://gitlab.cta-observatory.org/cta-computing/common/util/svn-port).

Can this ticket be made private, until the legal aspects are glass clear?

**Comment by maxnoe** [comment]
@dirk this does not add any information that is not already available in this repository. It just reduced the number of different spellings that appear in the log. There is really no point I  making this a GDPR issue. All this information was provided by the respective people in their commits already.

**Comment by maxnoe** [comment]
> The purpose of this list is not clear for me.

Then maybe just ask instead of starting a rant?

> sn261 has a real world name 

I specifically did not add information not already available in this repository.

If he / she wants to appear with a clear name in the log, they can add an entry to the mailmap.

**Comment by DirkHoffmann** [comment]
> This does not add any information that is not already available in this repository. It just reduced the number of different spellings that appear in the log. There is really no point I making this a GDPR issue. All this information was provided by the respective people in their commits already.

Then it cannot be made more exact or automatic indeed. 

Sorry, I did not want to start a rant. I suggested to improve the quality of information. 
You are right, with your target in mind, it should better remain as good or bad as the self-contained information is. Thanks for the explanations.

**Review by rlopezcoto — APPROVED** [review]

**Pull request merged**
