### PR TITLE
Reduce size of random forests in standard config

### PR DESCRIPTION
**Pull request by vuillaut**
Based on https://indico.cta-observatory.org/event/3992/

and cross-check on real-data from @SeiyaNozaki showing no diff in Crab spectra between the two configs.

### CODE REVIEW

**Review by maxnoe — APPROVED** [review]

**Comment by vuillaut** [comment]
- tests are failing for an unrelated issue
- I'd like to have an additional review

**Review by nbiederbeck — APPROVED** [review]

**Comment by vuillaut** [comment]
Why do I get this error on `test_create_dl3_energy_dependent_cuts` about gammapy?

**Comment by chaimain** [comment]
> Why do I get this error on `test_create_dl3_energy_dependent_cuts` about gammapy?

The error comes because the diffuse gamma events are very few (10) to create the energy-dependent IRFs with default/example config. Especially the theta values are almost all above the hard-coded max value of 0.32 deg. Will try to fix it.

**Comment by vuillaut** [comment]
> > Why do I get this error on `test_create_dl3_energy_dependent_cuts` about gammapy?
> 
> The error comes because the diffuse gamma events are very few (10) to create the energy-dependent IRFs with default/example config. Especially the theta values are almost all above the hard-coded max value of 0.32 deg. Will try to fix it.

Thank you for looking into this.

**Review by chaimain — APPROVED** [review]

**Comment by vuillaut** [comment]
Thank you very much @chaimain !

**Pull request merged**
