### PR TITLE
Fix rad max format

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Review by rlopezcoto — APPROVED** [review]

**Comment by chaimain** [comment]
With the restructuring of the tests in test_tools, it would be good to also do the same for test_create_dl3. Maybe I can add to this PR itself?

**Review by chaimain — APPROVED** [review]

**Comment by maxnoe** [comment]
@chaimain We removed all the pytest ordering stuff. Why did you add it back? And why does runing the different IRF tests depent on the other?

**Comment by maxnoe** [comment]
Edit: it seems I missed a couple of locations where pytest-ordering was still supposed to be used. 

I will fix those in a different PR. I'll revert your last commit.

**Comment by chaimain** [comment]
Ah! I think I didn't check the new change.

> Edit: no point in reverting, let's just fix the other ordering remnants in another PR

Ok.

**Pull request merged**
