### PR TITLE
Raise error when append node fails in merge, fixes #702

### LINKED ISSUE #702: Raise and error and exit with a non-0 exit code when merging h5 script cannot append files
To be aware of any problem that could arise in the merging process, e.g. 
```
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0001.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0002.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0003.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0004.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0005.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0006.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0007.h5
Can't append node dl2/event/telescope/parameters/LST_LSTCam from file /fefs/aswg/data/real/DL2/20201124/v0.7.1/tailcut84/dl2_LST-1.Run03071.0008.h5
```
it would be good to exit loudly the job with a non-0 exit code. Otherwise, these problems will pass unnoticed especially when running tons of batch jobs.

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by morcuended** [comment]
Thanks @maxnoe. Does the `raise` do the same as `sys.exit(1)`?

**Review by morcuended — APPROVED** [review]

**Comment by maxnoe** [comment]
> Thanks @maxnoe. Does the raise do the same as sys.exit(1)?

No, raise raises the original exception again, so we only log additional info here to help with the root cause and then raise the original error.

`sys.exit(1)` exits the current process with an exit code of 1. Which is not correct here, since we have a general function, not some `main` method. 

But since an unhandled exception will result in python exiting with an exit code of one, we get what we want: the traceback and the exit code of 1 for the tool.

**Comment by garciagenrique** [comment]
> > Thanks @maxnoe. Does the raise do the same as sys.exit(1)?
> 
> No, `raise` without any argument in an `except` block re-raises the original exception, so we only log additional info here to help with the root cause and then raise the original error.
> 
> `sys.exit(1)` exits the current process with an exit code of 1. Which is not correct here, since we have a general function, not some `main` method.
> 
> But since an unhandled exception will result in python exiting with an exit code of one, we get what we want: the traceback and the exit code of 1 for the tool.

Hi @maxnoe,
not sure that the behaviour you explained above is the desired.

Doing some final tests for the school I found that when a sub run gives an error, an `AssertionError` is raised but, the tool doesn't fail (does not exit with error 1).

Below I attach part of the log of the merging to 10 sub dl1 files (only 6 are finally merged)

```
Metadata CTAPIPE_IO_LST_VERSION does not exist in file electron/training/dl1_proton_20deg_180deg_run1047___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono.h5
electron/training/dl1_proton_20deg_180deg_run1047___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono.h5 cannot be merged '¯\_(ツ)_/¯'
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/lstchain/io/io.py", line 398, in merging_check
    check_mcheader(mcheader0, mcheader)
  File "/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/lstchain/io/io.py", line 771, in check_mcheader
    assert mcheader1[k] == mcheader2[k]
AssertionError
  0%|                                                                                                                                      | 0/6 [00:00<?, ?it/s]/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'geometry_LSTCam.__table_column_meta__'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'geometry_MAGICCam.__table_column_meta__'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'readout_LSTCam.__table_column_meta__'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'layout.__table_column_meta__'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'optics.__table_column_meta__'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'readout_MAGICCam.__table_column_meta__'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.65it/s]

```

**Comment by maxnoe** [comment]
@garciagenrique That's a completely independent issue. 

The behavior you describe is definitely intentional. The `automerge_h5_files` ignores mc files that it deems "incompatible" with the first file and does not abort when a file does not match.

Did you try to e.g. merge proton and gamma files?

**Comment by maxnoe** [comment]
Can you try with this branch here?
https://github.com/cta-observatory/cta-lstchain/compare/better_merge_errors?expand=1

That should give you a clear error message why the merge check is failing

**Comment by maxnoe** [comment]
I opened a new issue to discuss this, since it is not connected to this here.

**Pull request merged**
