### PR TITLE
Write array_info before opening hdfwriter

### PR DESCRIPTION
**Pull request by MaxNoe**
@rlopezcoto does this fix you issue?

### CODE REVIEW

**Comment by rlopezcoto** [comment]
no, still getting the same error... (we'll report later in more detail)

**Comment by MaxNoe** [comment]
Sorry, I didn't move it high enough. 

You need move the creation of the hdfwriter below the writing of the array info

**Comment by MaxNoe** [comment]
@rlopezcoto Could you try again?

**Comment by rlopezcoto** [comment]
yes, great!
it works perfectly for MC, for real data, it still does not for MC because it complains about:
```
    idx = np.zeros(max(subarray.tel_indices) + 1)
UnboundLocalError: local variable 'subarray' referenced before assignment
```
because `subarray` is currently defined within an `is_simu` if statement, but if that is solved, it should work out. Thanks!

**Comment by rlopezcoto** [comment]
Reason to move `write_array_info` and `HDF5TableWriter `:
@FrancaCassol reported a problem while opening a file and I reproduced it, either for the analysis of Read data or MC:
```
lstchain_data_r0_to_dl1 --infile LST-1.1.Run01967.0000.fits.fz --pedestal_path drs4_pedestal.Run1967.0000.fits --calibration_path calibration.Run1968.0000.hdf5 --time_calibration_path time_calibration.Run1968.0000.hdf5 -o ./
...
EXTRACTOR <ctapipe.image.extractor.GlobalPeakWindowSum object at 0x1a31a51710>
Traceback (most recent call last):
  File "/Users/rubenlopez/anaconda/envs/cta-dev/lib/python3.6/site-packages/h5py/_hl/files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rubenlopez/anaconda/envs/cta-dev/bin/lstchain_data_r0_to_dl1", line 11, in <module>
    load_entry_point('lstchain', 'console_scripts', 'lstchain_data_r0_to_dl1')()
  File "/Users/rlopezcoto/Code/ctasoft/fork/cta-lstchain/lstchain/scripts/lstchain_data_r0_to_dl1.py", line 126, in main
    tib_counter0=args.tib_counter0
  File "/Users/rlopezcoto/Code/ctasoft/fork/cta-lstchain/lstchain/reco/r0_to_dl1.py", line 280, in r0_to_dl1
    write_array_info(first_event, output_filename)
  File "/Users/rlopezcoto/Code/ctasoft/fork/cta-lstchain/lstchain/io/io.py", line 368, in write_array_info
    append=True
  File "/Users/rubenlopez/anaconda/envs/cta-dev/lib/python3.6/site-packages/astropy/table/connect.py", line 114, in __call__
    registry.write(instance, *args, **kwargs)
  File "/Users/rubenlopez/anaconda/envs/cta-dev/lib/python3.6/site-packages/astropy/io/registry.py", line 566, in write
    writer(data, *args, **kwargs)
  File "/Users/rubenlopez/anaconda/envs/cta-dev/lib/python3.6/site-packages/astropy/io/misc/hdf5.py", line 300, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
  File "/Users/rubenlopez/anaconda/envs/cta-dev/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/Users/rubenlopez/anaconda/envs/cta-dev/lib/python3.6/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './dl1_LST-1.1.Run01967.0000.fits.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = a02)
Closing remaining open files:./dl1_LST-1.1.Run01967.0000.fits.h5...done
```
@MaxNoe was not experiencing this problem (he is in Linux and I was running it in MacOS). We found a similar problem in https://github.com/h5py/h5py/issues/1101, but adding `export HDF5_USE_FILE_LOCKING='FALSE'` to the .bashrc did not solve the issue. Finally this was the solution.

**Comment by MaxNoe** [comment]
Ok, now it should work again for both MC and data, care to check @FrancaCassol or @rlopezcoto ?

**Comment by MaxNoe** [comment]
As a side note, it should not be necessary to get the first event to write this information.

All event sources are not required to provide subarray outside the event loop and the `SimTelEventsSource` also as the simtel runheader and the corsika run header before the event loop.

I'm not sure, if this is already the case for ctapipe 0.7 but somthing to keep in mind for the move to the next release.

**Comment by rlopezcoto** [comment]
I checked for both Data and MC and it works, thanks!

**Pull request merged**
