### PR TITLE
WIP: Fix notebooks to work on the lastest refactorings

### PR DESCRIPTION
**Pull request by misabelber**
Hi all,
I'm working on fixing the things that were not functioning in the notebooks due to the lastest changes (updating to ctapipe 0.6.2, coordinates refactoring, disp reconstruction changes).
Still a work in progress, I'm now working on adding the disp_parameters() method to the reconstruction.

### CODE REVIEW

**Comment by vuillaut** [comment]
Hi @misabelber 
Is this still in progress or should be closed?

**Comment by misabelber** [comment]
Still in progress but since there has been many changes lately, I will probably need to start again... Maybe we can close it for now until I have the time to return to it.

**Comment by vuillaut** [comment]
> Still in progress but since there has been many changes lately, I will probably need to start again... Maybe we can close it for now until I have the time to return to it.

If it's still in progress, you may leave it open, no problem there.
I am just going through the PR.

**Comment by vuillaut** [comment]
Hi @misabelber 
This might have been solved by PR #140, no?

**Comment by misabelber** [comment]
I think not really because notebooks which run the full chain are still outdated, but the truth is I don't know when I will have the time to take a look at that. Maybe they are not needed anymore since updated scripts exist, I don't know, perhaps we could close this PR to clean a bit, and later on  go back on those notebooks and decide which are useul and which can be deleted.

**Comment by vuillaut** [comment]
Ok then I close this one.
Thank you.

**Pull request closed without merging**
