### PR TITLE
Remove unused imports and fix docstring location

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by rlopezcoto** [comment]
Maybe the same here as #312, this may be in conflict with #304...

**Comment by MaxNoe** [comment]
Yes, but it's a small change and #304 needs conflict resolution anyways

**Comment by rlopezcoto** [comment]
Ok, so let's wait on @moralejo's opinion so we can decide where to merge them

**Comment by rlopezcoto** [comment]
After merging #304, could you please revise this and #312? There are currently conflicts and some of this was already implemented

**Comment by MaxNoe** [comment]
@rlopezcoto I rebased vs master

**Pull request merged**
