### PR TITLE
fix issue with nonposx

### PR DESCRIPTION
**Pull request by vuillaut**
current master is failing due to this

### CODE REVIEW

**Comment by maxnoe** [comment]
We should set our minimum matplotlib version accordingly

**Comment by rlopezcoto** [comment]
> We should set our minimum matplotlib version accordingly

whenever doing this, please remember to remove the old `pyparsing` version:
https://github.com/cta-observatory/cta-lstchain/issues/754

**Comment by maxnoe** [comment]
The new keywords require at least matplotlib 3.3 and the old ones got removed in 3.5: https://matplotlib.org/3.5.0/api/prev_api_changes/api_changes_3.3.0.html

**Comment by maxnoe** [comment]
conda-forge packages for mpl 3.5 are available, so we could require it: https://anaconda.org/conda-forge/matplotlib

**Comment by vuillaut** [comment]
bumped versions and removed pyparsing fixed version as requested, tests are now passing

**Review by rlopezcoto — APPROVED** [review]

**Pull request merged**
