### PR TITLE
smarter merge

### PR DESCRIPTION
**Pull request by vuillaut**
There has been a lot of issues with file merging lately, even with MC.
Part of it is that reduction to DL1 or DL2 does not always happen perfectly and smart merging assumed so.
This PR fix a bit of the issue, by removing files that do not include all the necessary datasets from the merging list, instead of assuming they all should be merged.

If not smart merge, only the common datasets are merged.

### CODE REVIEW

**Comment by morcuended** [comment]
I would say that the smart merge option still works only for MC data. `merging_check` function involves reading the mc information from the files and tables like /simulation/run_config are not present in real data files.

**Comment by vuillaut** [comment]
> I would say that the smart merge option still works only for MC data. `merging_check` function involves reading the mc information from the files and tables like /simulation/run_config are not present in real data files.

Yes indeed. Are you suggesting a change or shall we continue with `--smart False` in case of real data?
The other option I see is creating two different scripts for real and MC with the risk of divergence...

**Comment by morcuended** [comment]
Real data cannot be smart merged as far as I know. I don't know if it is a big problem.
If so, would it be possible to implement something similar for real data or adapt the existing one?

**Comment by vuillaut** [comment]
> Real data cannot be smart merged as far as I know. I don't know if it is a big problem.
> If so, would it be possible to implement something similar for real data or adapt the existing one?

Sorry what do you mean cannot be merged? After this PR?

**Comment by morcuended** [comment]
I realized that I did not clone the proper branch from your forked repo. Thus the smart option was still not working with real data. I will check again. Sorry for the noise.

**Comment by morcuended** [comment]
Run from this branch I think that `smart` option is still failing with real data. 

```
lstchain_merge_hdf5_files -d /home/daniel.morcuende/data/real/DL2/20191123/v0.4.5_v00 -o smart_merge_20191123.h5 --smart True --no-image True

Traceback (most recent call last):
  File "/home/daniel.morcuende/.conda/envs/smarter/bin/lstchain_merge_hdf5_files", line 11, in <module>
    load_entry_point('lstchain', 'console_scripts', 'lstchain_merge_hdf5_files')()
  File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/scripts/lstchain_merge_hdf5_files.py", line 48, in main
    smart_merge_h5files(file_list, args.outfile, node_keys=keys)
  File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/io/io.py", line 262, in smart_merge_h5files
    smart_list = merging_check(file_list)
  File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/io/io.py", line 233, in merging_check
    mcheader0 = read_simu_info_hdf5(filename0)
  File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/io/io.py", line 58, in read_simu_info_hdf5
    mc = next(mcheader)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 411, in read
    tab = self._setup_table(table_name, container)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 337, in _setup_table
    tab = self._h5file.get_node(table_name)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/file.py", line 432, in get_node
    node = self.node_factory(key)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/simulation/run_config``
```
May you confirm?

**Comment by vuillaut** [comment]
> Run from this branch I think that `smart` option is still failing with real data.
> 
> ```
> lstchain_merge_hdf5_files -d /home/daniel.morcuende/data/real/DL2/20191123/v0.4.5_v00 -o smart_merge_20191123.h5 --smart True --no-image True
> 
> Traceback (most recent call last):
>   File "/home/daniel.morcuende/.conda/envs/smarter/bin/lstchain_merge_hdf5_files", line 11, in <module>
>     load_entry_point('lstchain', 'console_scripts', 'lstchain_merge_hdf5_files')()
>   File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/scripts/lstchain_merge_hdf5_files.py", line 48, in main
>     smart_merge_h5files(file_list, args.outfile, node_keys=keys)
>   File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/io/io.py", line 262, in smart_merge_h5files
>     smart_list = merging_check(file_list)
>   File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/io/io.py", line 233, in merging_check
>     mcheader0 = read_simu_info_hdf5(filename0)
>   File "/fefs/home/daniel.morcuende/software/smarter-merge/cta-lstchain/lstchain/io/io.py", line 58, in read_simu_info_hdf5
>     mc = next(mcheader)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 411, in read
>     tab = self._setup_table(table_name, container)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 337, in _setup_table
>     tab = self._h5file.get_node(table_name)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/file.py", line 1642, in get_node
>     node = self._get_node(nodepath)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/file.py", line 1590, in _get_node
>     node = self._node_manager.get_node(nodepath)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/file.py", line 432, in get_node
>     node = self.node_factory(key)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/group.py", line 1178, in _g_load_child
>     node_type = self._g_check_has_child(childname)
>   File "/home/daniel.morcuende/.conda/envs/smarter/lib/python3.7/site-packages/tables/group.py", line 395, in _g_check_has_child
>     % (self._v_pathname, name))
> tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/simulation/run_config``
> ```
> 
> May you confirm?

I have not tested but this PR does not intend at solving the merging of real data issue so I would not be surprised.

**Pull request merged**
