### PR TITLE
Interpolate charge and peak time of bad pixels using neighbors in dl1ab step

### PR DESCRIPTION
**Pull request by SeiyaNozaki**
reopened instead of #716 

This PR enables to interpolate `image` and `peak_time` using good neighbors in dl1ab step.
First, clusters of bad pixels are labeled with good neighbors using `number_of_islands` function. The interpolation step can add a weighting based on the distance between a given bad pixel and good neighbors.

The interpolation is important when a proper `unusable_pixels` definition is applied (e.g. #969, #971, #990).

Any comments are welcome!

### CODE REVIEW

**Comment by maxnoe** [comment]
@SeiyaNozaki I made an initial PR in ctapipe, as this also came up with the FlashCam in simulations today: https://github.com/cta-observatory/ctapipe/pull/2023/

I would be happy if you can take a look.

**Comment by SeiyaNozaki** [comment]
thanks, I will have a look!

**Comment by maxnoe** [comment]
The ctapipe class is merged and was first released in 0.16.0

**Comment by SeiyaNozaki** [comment]
Since it was already implemented in ctapipe, I close this PR

**Pull request closed without merging**
