### PR TITLE
Adding script to reco from dl1 files

### PR DESCRIPTION
**Pull request by vuillaut**
I often find myself starting again from DL1 instead of DL0.
This script does the reconstruction from DL1 (it's almost a copy of `lst-recopipe.py`).

### CODE REVIEW

**Comment by rlopezcoto** [comment]
Hi, 
not sure if the almost duplication of a file is the best solution in this case. Wouldn't it be better to include a flag, that does not have any value by default (although I think that from dl0 to dl2 should be the default)?

**Comment by vuillaut** [comment]
Hi.
Yes, it's a good question and I asked myself the same.
I finally prefered this approach because `dl1 to dl2` is still something different from `dl0 to dl2` (maybe the scripts should be named this way rather than recopipe!).
But it's just a conceptual difference, I have no strong opinion there.

**Comment by vuillaut** [comment]
The best approach might be to have scripts for 
- `dl0_to_dl1`
- `dl1_to_dl2`
- `dl2_to_dl3`
- `dl0 to dl2` that just uses `dl0_to_dl1` and `dl1_to_dl2` 
- etc... 

?

**Comment by rlopezcoto** [comment]
Sounds like a good compromise. Not to multiply too much the number of scripts I would go for:

- `dl0_to_dl1`
- `dl1_to_dl2`
- `dl2_to_dl3`
- `dl0_to_dl3` (since we do not have the `dl2_to_dl3` script yet, it is ok to leave it up to dl2 now, but just to keep it in mind).
In any case, I think that the `recopipe` naming had some "historical" reason (maybe @misabelber can give us some words here). Otherwise, I'm happy with the solution.

**Comment by misabelber** [comment]
Hi! Yeah, I'm happy with the scripts Thomas is proposing regarding the needing to have access to each data level. The historical reason to have lst-recopipe its that it was a script destined to the user who wants to use already trained RFs over a raw data file (or simtel file in this case) without caring of the mid data levels. Apart from those scripts we will still need the one for training the RFs (either lst-trainpipe or lst-rfperformance, I personally alaways use lst-rfperformance because you can  actually check the performance plots of the RFs). We can also discuss the final name for those¿?. 
Also we should start adapting all these scripts to be used either in MC data or with real data as Thomas started in #181 .

**Comment by vuillaut** [comment]
I am closing this PR in favor of #203 (plus I seem to have messed up when merging master).

**Pull request closed without merging**
