### PR TITLE
quick data exploration and visualisation notebook

### PR DESCRIPTION
**Pull request by vuillaut**
Adding notebook to show how to do quick data exploration and visualisation with pandas using the dl1 files from cta-lstchain-extra

### CODE REVIEW

**Comment by rlopezcoto** [comment]
Maybe we should create a dedicated folder gathering notebooks for the bootcamp, is this notebook meant to be for that?

**Comment by misabelber** [comment]
Hi @vuillaut, I tried to run the notebooks that are already merged in the code(compare_chains, disp_visualisation, example_container), but I'm getting some errors when running them. Maybe is just that they are not complete, should I wait to the merge of a new version? Thanks!

**Comment by vuillaut** [comment]
Hi.
Thank you for your checks !
Could you indicate what errors you get please?
ps: This PR only adds one notebook. - Maybe you can open an issue or just contact me on slack to see what errors you have.

**Comment by rlopezcoto** [comment]
Ok I'll merge this one (@misabelber, you had problems with different notebooks as I see in #35 and #36, right?)

**Pull request merged**
