### PR TITLE
Fix drs4 pedestal plots

### PR DESCRIPTION
**Pull request by maxnoe**
Fix for the issue reported by @morcuended in slack

Plots for the test run are looking like this again now:
Screenshot_20211215_121827

### CODE REVIEW

**Review by morcuended — DISMISSED** [review]

**Comment by FrancaCassol** [comment]
Are we sure we want to re-calculate the offset value? 
I think we want to see the results with respect to what is supposed to be

**Comment by maxnoe** [comment]
> I think we want to see the results with respect to what is supposed to be

But we don't have that information anywhere, do we?

**Comment by FrancaCassol** [comment]
It was an input parameter

**Comment by maxnoe** [comment]
Yes, but how was it input? We just don't have the knowledge. The input parameter by the way was not used anymore in the current version of the code. It was overriden in the middle of the function by looking the value up in the event source, this is why I removed it.

I can also put it back.

**Comment by FrancaCassol** [comment]
> Yes, but how was it input? We just don't have the knowledge from the files. The input parameter by the way was not used anymore in the current version of the code. It was overriden in the middle of the function by looking the value up in the event source, this is why I removed it.

and what was wrong with that?

We want to arrive to release 0.8 as soon as possible, please minimise any change that is not strictly necessary

**Comment by maxnoe** [comment]
As you might remember, as you actually approved the corresponding PR, we removed the offset from the event source as it was double subtracted from both drs4 baseline and r0 waveform. So the `eventsource.r0_r1calibrator.offset` is 0.

**Comment by FrancaCassol** [comment]
Then leave the input parameter as it was before

**Comment by maxnoe** [comment]
> Then leave the input parameter as it was before

As it was before, it would be broken. We need to change *something* to make the plot work again. Leaving the offset hard coded to 400 does not seem like a good idea to me. Especially since @jsitarek requested to change it here #725.

**Comment by FrancaCassol** [comment]
I do not think we are going to change so often the offset, but this is your worry, one can simply add an argument to the onsite script.

**Comment by maxnoe** [comment]
Ok, I changed to using the supplied offset instead of the one used by the source.

I don't really understand why you think it's better to have the value passed by the user instead of calculating it from the input files.

The worst thing that can happen is that the drs4 pedestal file is broken, thus a wrong offset is used and thus the plot looks weird. Which is actually the reason the plot exists, to see if the drs4 pedestal file is ok.

**Comment by FrancaCassol** [comment]
Simply, for non experts it will be easier to see that data are far from the expected offset

**Review by FrancaCassol — DISMISSED** [review]

**Comment by moralejo** [comment]
A minor thing: "interp spikes" should now be "corrected spikes" or something similar, right?

**Comment by rlopezcoto** [comment]
>A minor thing: "interp spikes" should now be "corrected spikes" or something similar, right?
I included that. @FrancaCassol or @moralejo could you please re-approve?

**Review by FrancaCassol — APPROVED** [review]

**Pull request merged**
