### PR TITLE
Update muon script and calibration scripts

### PR DESCRIPTION
**Pull request by FrancaCassol**
This PR include
- the muon script is updated with the new gain selection and with tel_id information in order to be able to run it on old data.
- the calibration script get some new trailets which permit to select only the time or only the charge calibration 
- some other minors changes

### CODE REVIEW

**Comment by rlopezcoto** [comment]
So this one cancels #241?

**Comment by FrancaCassol** [comment]
Ops, yes, I will close it

**Comment by FrancaCassol** [comment]
Concerning the time calibration file, after discussion with @rlopezcoto  the idea is to create for each night a link (in the calibration directory)  to the correct time calibration file. This is performed by the onsite_create_calibration_script. 
The action is steered by the trailet "defaut_time_run".  If this trailet is set to zero, the script calculates the time calibration from the data of that night otherwise perform the link. The default value of the trailet is now 1625 with is the run suggested by Pawel as a good time run.

**Comment by rlopezcoto** [comment]
Hi @FrancaCassol, changes look good to me. This needs to be merged before the next release, so I'll leave it here for a while in case somebody has a comment, otherwise I'll merge it tonight.

**Comment by FrancaCassol** [comment]
ok!

**Pull request merged**
