### PR TITLE
Update dependencies to current versions, add python 3.11 CI

### PR DESCRIPTION
**Pull request by rlopezcoto**
There was a [gammapy release](https://github.com/gammapy/gammapy/releases/tag/v1.1) very recently and we can also follow the latest [ctapipe](https://github.com/cta-observatory/ctapipe/releases/tag/v0.19.2) one

### CODE REVIEW

**Comment by rlopezcoto** [comment]
it seems that the problem is still the support of python 3.8 in the ci due to the new version of gammapy, shall we drop it completely in the ci?

**Comment by maxnoe** [comment]
@rlopezcoto Yes, dropping 3.8 is fine.

Let's drop 3.8 and add a 3.11 test

**Comment by maxnoe** [comment]
Update scikit-learn to 1.2 for 3.11 support

**Comment by maxnoe** [comment]
aaaand matplotlib... current one is 3.7

**Comment by maxnoe** [comment]
The docs build also needs to run on at least 3.9 now

**Comment by rlopezcoto** [comment]
> aaaand matplotlib... current one is 3.7

just saw :D
the next one we downgrade to gammapy 1.0 and python 3.8 :P

**Comment by rlopezcoto** [comment]
> The docs build also needs to run on at least 3.9 now

what about pyflakes?

**Comment by maxnoe** [comment]
> what about pyflakes?

It should run on the lowest version we still support

**Comment by maxnoe** [comment]
Now it's numpy, which we for some reason pin to excatly 1.21, I think I'd just remove the pin

**Comment by maxnoe** [comment]
The setup.cfg still has 

>         'numpy<1.22.0a0',

**Comment by rlopezcoto** [comment]
I do not see that one, the only one to be modified should be:
https://github.com/cta-observatory/cta-lstchain/blob/7e0f1646cd682917a579407a98e21a2889a9b4c0/setup.cfg#L13
right?

**Comment by maxnoe** [comment]
Ah, I looked on Master, I probably already removed it in the 0.17 branch

**Comment by rlopezcoto** [comment]
uff, it was tougher than it seemed, thanks for the help @maxnoe !

**Review by maxnoe — APPROVED** [review]

**Pull request merged**
