### PR TITLE
Require ctapipe_io_lst 0.23, add evb preprocessing to run summary

### PR DESCRIPTION
**Pull request by maxnoe**
This updates to ctapipe_io_lst, which includes the parsing of the EVB preprocessing steps.

This is also stored into the runsummary.

To not completely dominate the run summary with the string representation, I put the integer value and only for MONO events.

Here is how you can get something more human readable from that:

```
In [1]: from ctapipe_io_lst.evb_preprocessing import EVBPreprocessingFlag

In [2]: EVBPreprocessingFlag(103)
Out[2]: <EVBPreprocessingFlag.GAIN_SELECTION|BASELINE_SUBTRACTION|DELTA_T_CORRECTION|PEDESTAL_SUBTRACTION|PE_CALIBRATION: 103>

In [3]: EVBPreprocessingFlag(3)
Out[3]: <EVBPreprocessingFlag.GAIN_SELECTION|BASELINE_SUBTRACTION: 3>

In [4]: EVBPreprocessingFlag(2)
Out[4]: <EVBPreprocessingFlag.BASELINE_SUBTRACTION: 2>
```

### CODE REVIEW

**Review by rlopezcoto — DISMISSED** [review]

**Comment by morcuended** [comment]
latest ctapipe io lst in condaforge is 0.22.6, that's why tests are failing

**Comment by moralejo** [comment]
> latest ctapipe io lst in condaforge is 0.22.6, that's why tests are failing (in the mamba setup)

It is there now, yet it keeps failing with the same error...

**Comment by rlopezcoto** [comment]
the pedestal file in the test is giving some trouble, probably related to the new implementation of the ctapipe_io_lst reading

**Comment by maxnoe** [comment]
Should be fixed now

**Comment by rlopezcoto** [comment]
Great, thanks!

**Review by rlopezcoto — APPROVED** [review]

**Pull request merged**
