### PR TITLE
Fix an error while processing prod5 MC

### PR DESCRIPTION
**Pull request by mari-taka**
There was a bug while trying to run lstchain_mc_r0_to_dl1 script to prod5 MC. [issue #514 ](https://github.com/cta-observatory/cta-lstchain/issues/514)
I modified `write_array_info_08` function like `write_array_info` function and became to be able to process the prod5 MC.

### CODE REVIEW

**Comment by rlopezcoto** [comment]
thanks @mari-taka
could you please add a comment in the code saying that this is a temporary solution until we move to ctapipe v0.9.1?

**Comment by mari-taka** [comment]
@rlopezcoto I add a comment that says the new function is a temporary solution. What would you think?

**Comment by maxnoe** [comment]
Please also open an issue when this is merged. TODOs in code are less visible then issues, especially when issues are linked to a milestone.

**Comment by rlopezcoto** [comment]
hi @mari-taka the comment is ok, but the proposed solution is not passing travis continuous integration, it seems that there is some problem with the writing of the dataframes inside the file with the modified function, could you please check?

**Comment by rlopezcoto** [comment]
see #540

**Pull request closed without merging**
